---
title: "Python Cheat Sheets-0002-Strings-MasoudF"
output: 
  html_document:
    code_folding: show
    theme:
      bg: "#202123"
      fg: "#B8BCC2"
      primary: "#EA80FC"
      secondary: "#00DAC6"
      base_font:
        google: Prompt
      heading_font:
        google: Proza Libre
---

```{r setup, include=FALSE}
if (requireNamespace("thematic")) 
  thematic::thematic_rmd(font = "auto")
library(reticulate)
reticulate::use_python("C:/Program Files/Python310/python.exe")
```

 

## <span style="color:red"> Python Lists </span> {.tabset .tabset-pills}

### Lists

Lists are used to store multiple items in a single variable.

Lists are one of 4 built-in data types in Python used to store collections of data, the other 3 are Tuple, Set, and Dictionary, all with different qualities and usage.

Lists are created using square brackets:
```{python}
thislist = ["apple", "banana", "cherry"]
print(thislist)

```




<span style="color:green">
List Items:
</span>
List items are ordered, changeable, and allow duplicate values.

List items are indexed, the first item has index [0], the second item has index [1] etc.

```{python}
thislist = ["apple", "banana", "cherry"]
print(thislist)

```

<span style="color:green">
Ordered: 
</span>
When we say that lists are ordered, it means that the items have a defined order, and that order will not change.

If you add new items to a list, the new items will be placed at the end of the list.

Note: There are some list methods that will change the order, but in general: the order of the items will not change.

<span style="color:green">
Changeable: 
</span>
The list is changeable, meaning that we can change, add, and remove items in a list after it has been created.


<span style="color:green">
Allow Duplicates: 
</span>
Since lists are indexed, lists can have items with the same value:

```{python}
#Lists allow duplicate values:
thislist = ["apple", "banana", "cherry", "apple", "cherry"]
print(thislist)
```



### Basic commands

#### <span style="color:green"> List Length </span>

To determine how many items a list has, use the len() function:

```{python}
#Print the number of items in the list:
thislist = ["apple", "banana", "cherry"]
print(len(thislist))
```

#### <span style="color:green"> List Items - Data Types </span>


List items can be of any data type:
```{python}
#Example
#String, int and boolean data types:

list1 = ["apple", "banana", "cherry"]
list2 = [1, 5, 7, 9, 3]
list3 = [True, False, False]
```

A list can contain different data types:

```{python}
#Example
#A list with strings, integers and boolean values:
list1 = ["abc", 34, True, 40, "male"]
```


#### <span style="color:green">  </span>

type()

From Python's perspective, lists are defined as objects with the data type 'list':

<class 'list'>

```{python}
#What is the data type of a list?
mylist = ["apple", "banana", "cherry"]
print(type(mylist))

```


#### <span style="color:green"> The list() Constructor </span>

It is also possible to use the list() constructor when creating a new list.


```{python}
#Example
#Using the list() constructor to make a List:
thislist = list(("apple", "banana", "cherry")) # note the double round-brackets
print(thislist)

```



###  Python Collections (Arrays)

There are four collection data types in the Python programming language:

* List is a collection which is ordered and changeable. Allows duplicate members.
* Tuple is a collection which is ordered and unchangeable. Allows duplicate members.
* Set is a collection which is unordered, unchangeable*, and unindexed. No duplicate members.
* Dictionary is a collection which is ordered** and changeable. No duplicate members.

<span style="color:yellow">
Set items are unchangeable, but you can remove and/or add items whenever you like.
</span>

<span style="color:yellow">
As of Python version 3.7, dictionaries are ordered. In Python 3.6 and earlier, dictionaries are unordered.
</span>

When choosing a collection type, it is useful to understand the properties of that type. Choosing the right type for a particular data set could mean retention of meaning, and, it could mean an increase in efficiency or security.



###  Python - Access List Items 

#### <span style="color:green"> Access Items </span>

List items are indexed and you can access them by referring to the index number:



```{python}
#Example
#Print the second item of the list:
thislist = ["apple", "banana", "cherry"]
print(thislist[1])

```

<span style="color:yellow"> Note: The first item has index 0. </span>

#### <span style="color:green"> Negative Indexing </span>


Negative indexing means start from the end

-1 refers to the last item, -2 refers to the second last item etc.


```{python}
#Example
#Print the last item of the list:
thislist = ["apple", "banana", "cherry"]
print(thislist[-1])

```

#### <span style="color:green"> Range of Indexes </span>

You can specify a range of indexes by specifying where to start and where to end the range.

When specifying a range, the return value will be a new list with the specified items.


```{python}
#Example
#Return the third, fourth, and fifth item:
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(thislist[2:5])

```

<span style="color:yellow"> 
Note: The search will start at index 2 (included) and end at index 5 (not included).
</span>

<span style="color:yellow"> 
Remember that the first item has index 0.
</span>


By leaving out the start value, the range will start at the first item:


```{python}
#Example
#This example returns the items from the beginning to, but NOT including, "kiwi":
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(thislist[:4])

```


By leaving out the end value, the range will go on to the end of the list:



```{python}
#Example
#This example returns the items from "cherry" to the end:
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(thislist[2:])

```

#### <span style="color:green"> Range of Negative Indexes </span>

Specify negative indexes if you want to start the search from the end of the list:


```{python}
#Example
#This example returns the items from "orange" (-4) to, but NOT including "mango" (-1):
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(thislist[-4:-1])

```


#### <span style="color:green"> Check if Item Exists </span>

To determine if a specified item is present in a list use the in keyword:


```{python}
#Example
#Check if "apple" is present in the list:
thislist = ["apple", "banana", "cherry"]
if "apple" in thislist:
  print("Yes, 'apple' is in the fruits list")
```


### Python - Change List Items



#### <span style="color:green"> Change Item Value </span>

To change the value of a specific item, refer to the index number:

```{python}
#Example
#Change the second item:
thislist = ["apple", "banana", "cherry"]
thislist[1] = "blackcurrant"
print(thislist)

```


#### <span style="color:green"> Change a Range of Item Values </span>



To change the value of items within a specific range, define a list with the new values, and refer to the range of index numbers where you want to insert the new values:



```{python}
#Example
#Change the values "banana" and "cherry" with the values "blackcurrant" and "watermelon":

thislist = ["apple", "banana", "cherry", "orange", "kiwi", "mango"]
thislist[1:3] = ["blackcurrant", "watermelon"]
print(thislist)

```

If you insert more items than you replace, the new items will be inserted where you specified, and the remaining items will move accordingly:




```{python}
#Example
#Change the second value by replacing it with two new values:
thislist = ["apple", "banana", "cherry"]
thislist[1:2] = ["blackcurrant", "watermelon"]
print(thislist)

```

<span style="color:yellow"> 
Note: The length of the list will change when the number of items inserted does not match the number of items replaced.
</span>


If you insert less items than you replace, the new items will be inserted where you specified, and the remaining items will move accordingly:




```{python}
#Example
#Change the second and third value by replacing it with one value:

thislist = ["apple", "banana", "cherry"]
thislist[1:3] = ["watermelon"]
print(thislist)

```




#### <span style="color:green"> Insert Items </span>

To insert a new list item, without replacing any of the existing values, we can use the insert() method.

The insert() method inserts an item at the specified index:



```{python}
#Example
#Insert "watermelon" as the third item:
thislist = ["apple", "banana", "cherry"]
thislist.insert(2, "watermelon")
print(thislist)

```

<span style="color:yellow"> 
Note: As a result of the example above, the list will now contain 4 items.
</span>


### Python - Add List Items


#### <span style="color:green"> Append Items </span>

To add an item to the end of the list, use the append() method:


```{python}
#Example
#Using the append() method to append an item:
thislist = ["apple", "banana", "cherry"]
thislist.append("orange")
print(thislist)

```




#### <span style="color:green"> Insert Items </span>

To insert a list item at a specified index, use the insert() method.

The insert() method inserts an item at the specified index:



```{python}
#Example
#Insert an item as the second position:
thislist = ["apple", "banana", "cherry"]
thislist.insert(1, "orange")
print(thislist)

```

<span style="color:yellow"> 
Note: As a result of the examples above, the lists will now contain 4 items.
</span>

#### <span style="color:green"> Extend List </span>


To append elements from another list to the current list, use the extend() method.

```{python}
#Example
#Add the elements of tropical to thislist:

thislist = ["apple", "banana", "cherry"]
tropical = ["mango", "pineapple", "papaya"]
thislist.extend(tropical)
print(thislist)

```

The elements will be added to the end of the list.





#### <span style="color:green"> Add Any Iterable </span>


The extend() method does not have to append lists, you can add any iterable object (tuples, sets, dictionaries etc.).


```{python}
#Example
#Add elements of a tuple to a list:

thislist = ["apple", "banana", "cherry"]
thistuple = ("kiwi", "orange")
thislist.extend(thistuple)
print(thislist)

```



### Python - Remove List Items

#### <span style="color:green"> Remove Specified Item </span>


The remove() method removes the specified item.

```{python}
#Example
#Remove "banana":
thislist = ["apple", "banana", "cherry"]
thislist.remove("banana")
print(thislist)

```


#### <span style="color:green"> Remove Specified Index </span>

The pop() method removes the specified index.

```{python}
#Example
#Remove the second item:
thislist = ["apple", "banana", "cherry"]
thislist.pop(1)
print(thislist)

```


If you do not specify the index, the pop() method removes the last item.

```{python}
#Example
#Remove the last item:
thislist = ["apple", "banana", "cherry"]
thislist.pop()
print(thislist)

```

The del keyword also removes the specified index:

```{python}
#Example
#Remove the first item:
thislist = ["apple", "banana", "cherry"]
del thislist[0]
print(thislist)

```

The del keyword can also delete the list completely.

```{python}
#Example
#Delete the entire list:
thislist = ["apple", "banana", "cherry"]
del thislist

```

#### <span style="color:green"> Clear the List </span>

The clear() method empties the list.

The list still remains, but it has no content.

```{python}
#Example
#Clear the list content:
thislist = ["apple", "banana", "cherry"]
thislist.clear()
print(thislist)

```



### Python - Loop Lists

#### <span style="color:green"> Loop Through a List </span>

You can loop through the list items by using a for loop:

```{python}
#Example
#Print all items in the list, one by one:
thislist = ["apple", "banana", "cherry"]
for x in thislist:
  print(x)

```

Learn more about for loops in our Python For Loops Chapter.

#### <span style="color:green"> Loop Through the Index Numbers </span>

You can also loop through the list items by referring to their index number.

Use the range() and len() functions to create a suitable iterable.

```{python}
#Example
#Print all items by referring to their index number:
thislist = ["apple", "banana", "cherry"]
for i in range(len(thislist)):
  print(thislist[i])

```

The iterable created in the example above is [0, 1, 2].

#### <span style="color:green"> Using a While Loop </span>


You can loop through the list items by using a while loop.

Use the len() function to determine the length of the list, then start at 0 and loop your way through the list items by refering to their indexes.

Remember to increase the index by 1 after each iteration.

```{python}
#Example
#Print all items, using a while loop to go through all the index numbers
thislist = ["apple", "banana", "cherry"]
i = 0
while i < len(thislist):
  print(thislist[i])
  i = i + 1

```

Learn more about while loops in our Python While Loops Chapter.

#### <span style="color:green"> Looping Using List Comprehension </span>

List Comprehension offers the shortest syntax for looping through lists:

```{python}
#Example
#A short hand for loop that will print all items in a list:

thislist = ["apple", "banana", "cherry"]
[print(x) for x in thislist]

```


### Python - List Comprehension

#### <span style="color:green"> List Comprehension </span>

List comprehension offers a shorter syntax when you want to create a new list based on the values of an existing list.

Example:

Based on a list of fruits, you want a new list, containing only the fruits with the letter "a" in the name.

Without list comprehension you will have to write a for statement with a conditional test inside:
```{python}
#Example
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
newlist = []

for x in fruits:
  if "a" in x:
    newlist.append(x)

print(newlist)

```

With list comprehension you can do all that with only one line of code:

```{python}
#Example
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]

newlist = [x for x in fruits if "a" in x]

print(newlist)

```


#### <span style="color:green"> The Syntax </span>

<span style="color:yellow"> 
newlist = [expression for item in iterable if condition == True]
</span>




The return value is a new list, leaving the old list unchanged.

#### <span style="color:green"> Condition </span>

The condition is like a filter that only accepts the items that valuate to True.
```{python}
#Example
#Only accept items that are not "apple":
newlist = [x for x in fruits if x != "apple"]
print(newlist)
```

The condition if x != "apple"  will return True for all elements other than "apple", making the new list contain all fruits except "apple".

The condition is optional and can be omitted:
```{python}
#Example
#With no if statement:
newlist = [x for x in fruits]
print(newlist)
```


#### <span style="color:green"> Iterable </span>

The iterable can be any iterable object, like a list, tuple, set etc.

Example

You can use the range() function to create an iterable:



```{python}
newlist = [x for x in range(10)]
print(newlist)
```
Same example, but with a condition:

Example

Accept only numbers lower than 5:

```{python}
newlist = [x for x in range(10) if x < 5]
print(newlist)
```


#### <span style="color:green"> Expression </span>

The expression is the current item in the iteration, but it is also the outcome, which you can manipulate before it ends up like a list item in the new list:

Example

Set the values in the new list to upper case:

```{python}
newlist = [x.upper() for x in fruits]
print(newlist)
```

You can set the outcome to whatever you like:

Example

Set all values in the new list to 'hello':
```{python}
newlist = ['hello' for x in fruits]
print(newlist)
```

The expression can also contain conditions, not like a filter, but as a way to manipulate the outcome:

```{python}
#Example
#Return "orange" instead of "banana":

newlist = [x if x != "banana" else "orange" for x in fruits]
print(newlist)
```

The expression in the example above says:

"Return the item if it is not banana, if it is banana return orange".





### Sort List Alphanumerically



List objects have a sort() method that will sort the list alphanumerically, ascending, by default:
```{python}
#Example
#Sort the list alphabetically:

thislist = ["orange", "mango", "kiwi", "pineapple", "banana"]
thislist.sort()
print(thislist)
```


```{python}
#Example
#Sort the list numerically:

thislist = [100, 50, 65, 82, 23]
thislist.sort()
print(thislist)
```

#### <span style="color:orange"> Sort Descending </span>

To sort descending, use the keyword argument reverse = True:

```{python}
#Example
#Sort the list descending:

thislist = ["orange", "mango", "kiwi", "pineapple", "banana"]
thislist.sort(reverse = True)
print(thislist)
```



```{python}
#Example
#Sort the list descending:
thislist = [100, 50, 65, 82, 23]
thislist.sort(reverse = True)
print(thislist)
```

#### <span style="color:orange"> Customize Sort Function </span>

You can also customize your own function by using the keyword argument key = function.

The function will return a number that will be used to sort the list (the lowest number first):

```{python}
#Example
#Sort the list based on how close the number is to 50:

def myfunc(n):
  return abs(n - 50)

thislist = [100, 50, 65, 82, 23]
thislist.sort(key = myfunc)
print(thislist)
```


#### <span style="color:orange"> Case Insensitive Sort </span>

By default the sort() method is case sensitive, resulting in all capital letters being sorted before lower case letters:



```{python}
#Example
#Case sensitive sorting can give an unexpected result:

thislist = ["banana", "Orange", "Kiwi", "cherry"]
thislist.sort()
print(thislist)
```

Luckily we can use built-in functions as key functions when sorting a list.

So if you want a case-insensitive sort function, use str.lower as a key function:

```{python}
#Example
#Perform a case-insensitive sort of the list:
thislist = ["banana", "Orange", "Kiwi", "cherry"]
thislist.sort(key = str.lower)
print(thislist)
```

#### <span style="color:orange"> Reverse Order </span>

What if you want to reverse the order of a list, regardless of the alphabet?

The reverse() method reverses the current sorting order of the elements.


```{python}
#Example
#Reverse the order of the list items:
thislist = ["banana", "Orange", "Kiwi", "cherry"]
thislist.reverse()
print(thislist)
```


### Python - Copy Lists

#### <span style="color:orange"> Copy a List </span>

You cannot copy a list simply by typing list2 = list1, because: list2 will only be a reference to list1, and changes made in list1 will automatically also be made in list2.

There are ways to make a copy, one way is to use the built-in List method copy().

```{python}
#Example
#Make a copy of a list with the copy() method:

thislist = ["apple", "banana", "cherry"]
mylist = thislist.copy()
print(mylist)
```

Another way to make a copy is to use the built-in method list().

```{python}
#Example
#Make a copy of a list with the list() method:

thislist = ["apple", "banana", "cherry"]
mylist = list(thislist)
print(mylist) 
```



### Join Two Lists


There are several ways to join, or concatenate, two or more lists in Python.

One of the easiest ways are by using the + operator.


```{python}
#Example
#Join two list:

list1 = ["a", "b", "c"]
list2 = [1, 2, 3]

list3 = list1 + list2
print(list3)
```

Another way to join two lists is by appending all the items from list2 into list1, one by one:


```{python}
#Example
#Append list2 into list1:

list1 = ["a", "b" , "c"]
list2 = [1, 2, 3]

for x in list2:
  list1.append(x)

print(list1)
```

Or you can use the extend() method, which purpose is to add elements from one list to another list:


```{python}
#Example
#Use the extend() method to add list2 at the end of list1:

list1 = ["a", "b" , "c"]
list2 = [1, 2, 3]

list1.extend(list2)
print(list1)
```




## Contact us

Contact me at masoudfaridi@modares.ac.ir or masoud1faridi@gmail.com

