---
title: "Python Cheat Sheets-0002-Strings-MasoudF"
output: 
  html_document:
    code_folding: show
    theme:
      bg: "#202123"
      fg: "#B8BCC2"
      primary: "#EA80FC"
      secondary: "#00DAC6"
      base_font:
        google: Prompt
      heading_font:
        google: Proza Libre
---

```{r setup, include=FALSE}
if (requireNamespace("thematic")) 
  thematic::thematic_rmd(font = "auto")
library(reticulate)
reticulate::use_python("C:/Program Files/Python310/python.exe")
```

## <span style="color:orange">  Python Tuples </span> {.tabset .tabset-pills}




###   Tuple 


```{python}
mytuple = ("apple", "banana", "cherry")
print(mytuple)
```

* Tuples are used to store multiple items in a single variable.

* Tuple is one of 4 built-in data types in Python used to store collections of data, the other 3 are List, Set, and Dictionary, all with different qualities and usage.

* A tuple is a collection which is ordered and unchangeable.

* Tuples are written with round brackets. 


```{python}
#Example
#Create a Tuple:

thistuple = ("apple", "banana", "cherry")
print(thistuple)

```

#### <span style="color:orange"> Tuple Items </span>

Tuple items are ordered, unchangeable, and allow duplicate values.

Tuple items are indexed, the first item has index [0], the second item has index [1] etc.

#### <span style="color:orange"> Ordered </span>

When we say that tuples are ordered, it means that the items have a defined order, and that order will not change.

#### <span style="color:orange"> Unchangeable </span>

Tuples are unchangeable, meaning that we cannot change, add or remove items after the tuple has been created.


#### <span style="color:orange"> Allow Duplicates </span>

Since tuples are indexed, they can have items with the same value:

```{python}
#Example
#Tuples allow duplicate values:

thistuple = ("apple", "banana", "cherry", "apple", "cherry")
print(thistuple)

```




#### <span style="color:orange"> Tuple Length </span>

To determine how many items a tuple has, use the len() function:

```{python}
#Example
#Print the number of items in the tuple:

thistuple = ("apple", "banana", "cherry")
print(len(thistuple))

```

#### <span style="color:orange"> Create Tuple With One Item </span>

To create a tuple with only one item, you have to add a comma after the item, otherwise Python will not recognize it as a tuple.

```{python}
#Example
#One item tuple, remember the comma:

thistuple = ("apple",)
print(type(thistuple))
#NOT a tuple
thistuple = ("apple")
print(type(thistuple))
```



#### <span style="color:orange"> Tuple Items - Data Types </span>

Tuple items can be of any data type:

```{python}
#Example
#String, int and boolean data types:

tuple1 = ("apple", "banana", "cherry")
tuple2 = (1, 5, 7, 9, 3)
tuple3 = (True, False, False)

```


A tuple can contain different data types:

```{python}
#Example
#A tuple with strings, integers and boolean values:

tuple1 = ("abc", 34, True, 40, "male")


```

#### <span style="color:orange"> type() </span>


From Python's perspective, tuples are defined as objects with the data type 'tuple':

```{python}
#<class 'tuple'>
#Example
#What is the data type of a tuple?

mytuple = ("apple", "banana", "cherry")
print(type(mytuple))

```

#### <span style="color:orange"> The tuple() Constructor </span>


It is also possible to use the tuple() constructor to make a tuple.

```{python}
#Example
#Using the tuple() method to make a tuple:

thistuple = tuple(("apple", "banana", "cherry")) # note the double round-brackets
print(thistuple)

```


#### <span style="color:orange"> Python Collections (Arrays) </span>

There are four collection data types in the Python programming language:

* List is a collection which is ordered and changeable. Allows duplicate members.
* Tuple is a collection which is ordered and unchangeable. Allows duplicate members.
* Set is a collection which is unordered, unchangeable*, and unindexed. No duplicate members.
* Dictionary is a collection which is ordered** and changeable. No duplicate members.

<span style="color:yellow">
* Set items are unchangeable, but you can remove and/or add items whenever you like.
</span>

<span style="color:yellow">
* As of Python version 3.7, dictionaries are ordered. In Python 3.6 and earlier, dictionaries are unordered.
</span>

When choosing a collection type, it is useful to understand the properties of that type. Choosing the right type for a particular data set could mean retention of meaning, and, it could mean an increase in efficiency or security.




### Access Tuple Items


#### <span style="color:orange"> Python - Access Tuple Items </span>


You can access tuple items by referring to the index number, inside square brackets:

```{python}
#Example
#Print the second item in the tuple:

thistuple = ("apple", "banana", "cherry")
print(thistuple[1])

```

<span style="color:orange">
Note: The first item has index 0.
</span>

#### <span style="color:orange"> Negative Indexing </span>


Negative indexing means start from the end.

-1 refers to the last item, -2 refers to the second last item etc.

```{python}
#Example
#Print the last item of the tuple:

thistuple = ("apple", "banana", "cherry")
print(thistuple[-1])

```


#### <span style="color:orange"> Range of Indexes </span>

You can specify a range of indexes by specifying where to start and where to end the range.

When specifying a range, the return value will be a new tuple with the specified items.

```{python}
#Example
#Return the third, fourth, and fifth item:

thistuple = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
print(thistuple[2:5])

```

<span style="color:yellow">
Note: The search will start at index 2 (included) and end at index 5 (not included).
</span>

Remember that the first item has index 0.

By leaving out the start value, the range will start at the first item:

```{python}
#Example
#This example returns the items from the beginning to, but NOT included, "kiwi":

thistuple = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
print(thistuple[:4])

```


By leaving out the end value, the range will go on to the end of the list:

```{python}
#Example
#This example returns the items from "cherry" and to the end:

thistuple = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
print(thistuple[2:])

```

#### <span style="color:orange"> Range of Negative Indexes </span>

Specify negative indexes if you want to start the search from the end of the tuple:

```{python}
#Example
#This example returns the items from index -4 (included) to index -1 (excluded)

thistuple = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
print(thistuple[-4:-1])

```



#### <span style="color:orange"> Check if Item Exists </span>

To determine if a specified item is present in a tuple use the in keyword:

```{python}
#Example
#Check if "apple" is present in the tuple:

thistuple = ("apple", "banana", "cherry")
if "apple" in thistuple:
  print("Yes, 'apple' is in the fruits tuple")

```


	
### Update Tuples

Tuples are unchangeable, meaning that you cannot change, add, or remove items once the tuple is created.

But there are some workarounds.

#### <span style="color:orange"> Change Tuple Values </span>

Once a tuple is created, you cannot change its values. Tuples are unchangeable, or immutable as it also is called.

But there is a workaround. You can convert the tuple into a list, change the list, and convert the list back into a tuple.


```{python}
#Example
#Convert the tuple into a list to be able to change it:

x = ("apple", "banana", "cherry")
y = list(x)
y[1] = "kiwi"
x = tuple(y)

print(x)

```



#### <span style="color:orange"> Add Items  </span>

Since tuples are immutable, they do not have a build-in append() method, but there are other ways to add items to a tuple.

1. Convert into a list: Just like the workaround for changing a tuple, you can convert it into a list, add your item(s), and convert it back into a tuple.

```{python}
#Example
#Convert the tuple into a list, add "orange", and convert it back into a tuple:

thistuple = ("apple", "banana", "cherry")
y = list(thistuple)
y.append("orange")
thistuple = tuple(y)

```


2. Add tuple to a tuple. You are allowed to add tuples to tuples, so if you want to add one item, (or many), create a new tuple with the item(s), and add it to the existing tuple:

```{python}
#Example
#Create a new tuple with the value "orange", and add that tuple:

thistuple = ("apple", "banana", "cherry")
y = ("orange",)
thistuple += y

print(thistuple)

```


Note: When creating a tuple with only one item, remember to include a comma after the item, otherwise it will not be identified as a tuple.

#### <span style="color:orange"> Remove Items </span>


Note: You cannot remove items in a tuple.

Tuples are unchangeable, so you cannot remove items from it, but you can use the same workaround as we used for changing and adding tuple items:

```{python}
#Example
#Convert the tuple into a list, remove "apple", and convert it back into a tuple:

thistuple = ("apple", "banana", "cherry")
y = list(thistuple)
y.remove("apple")
thistuple = tuple(y)

```


Or you can delete the tuple completely:

```{python}
#Example
#The del keyword can delete the tuple completely:

thistuple = ("apple", "banana", "cherry")
del thistuple
#print(thistuple) #this will raise an error because the tuple no longer exists

```



### Unpack Tuples

#### <span style="color:orange"> Unpacking a Tuple </span>

When we create a tuple, we normally assign values to it. This is called "packing" a tuple:

```{python}
#Example
#Packing a tuple:

fruits = ("apple", "banana", "cherry")

```

But, in Python, we are also allowed to extract the values back into variables. This is called "unpacking":


```{python}
#Example
#Unpacking a tuple:

fruits = ("apple", "banana", "cherry")

(green, yellow, red) = fruits

print(green)
print(yellow)
print(red)

```


<span style="color:yellow"> 
Note: The number of variables must match the number of values in the tuple, if not, you must use an asterisk to collect the remaining values as a list.
</span>



#### <span style="color:orange">Using Asterisk* </span>


If the number of variables is less than the number of values, you can add an * to the variable name and the values will be assigned to the variable as a list:


```{python}
#Example
#Assign the rest of the values as a list called "red":

fruits = ("apple", "banana", "cherry", "strawberry", "raspberry")

(green, yellow, *red) = fruits

print(green)
print(yellow)
print(red)

```


If the asterisk is added to another variable name than the last, Python will assign values to the variable until the number of values left matches the number of variables left.


```{python}
#Example
#Add a list of values the "tropic" variable:

fruits = ("apple", "mango", "papaya", "pineapple", "cherry")

(green, *tropic, red) = fruits

print(green)
print(tropic)
print(red)

```


	
### Loop Tuples

#### <span style="color:orange">Loop Through a Tuple </span>


You can loop through the tuple items by using a for loop.

```{python}
#Example
#Iterate through the items and print the values:

thistuple = ("apple", "banana", "cherry")
for x in thistuple:
  print(x)

```


Learn more about for loops in our Python For Loops Chapter.

#### <span style="color:orange">Loop Through the Index Numbers </span>

You can also loop through the tuple items by referring to their index number.

Use the range() and len() functions to create a suitable iterable.

```{python}
#Example
#Print all items by referring to their index number:

thistuple = ("apple", "banana", "cherry")
for i in range(len(thistuple)):
  print(thistuple[i])


```



#### <span style="color:orange">Using a While Loop </span>

You can loop through the list items by using a while loop.

Use the len() function to determine the length of the tuple, then start at 0 and loop your way through the tuple items by refering to their indexes.

Remember to increase the index by 1 after each iteration.

```{python}
#Example
#Print all items, using a while loop to go through all the index numbers:

thistuple = ("apple", "banana", "cherry")
i = 0
while i < len(thistuple):
  print(thistuple[i])
  i = i + 1

```




### Join Tuples



#### <span style="color:orange"> Join Two Tuples</span>

To join two or more tuples you can use the + operator:

```{python}
#Example
#Join two tuples:

tuple1 = ("a", "b" , "c")
tuple2 = (1, 2, 3)

tuple3 = tuple1 + tuple2
print(tuple3)

```


#### <span style="color:orange">Multiply Tuples </span>

If you want to multiply the content of a tuple a given number of times, you can use the * operator:

```{python}
#Example
#Multiply the fruits tuple by 2:

fruits = ("apple", "banana", "cherry")
mytuple = fruits * 2

print(mytuple)

```




### Tuple Methods {.tabset .tabset-pills}

Python has two built-in methods that you can use on tuples.

$$
\begin{array}{c|c}
\text{Method} & \text{Description}  \\ \hline
\text{count()} & \text{	Returns the number of times a specified value occurs in a tuple}  \\ 
\text{index()} & \text{Searches the tuple for a specified value and returns the position of where it was found} 
\end{array}
$$


#### count() 


##### <span style="color:orange"> Python Tuple count() Method </span>	


```{python}
#Example
#Return the number of times the value 5 appears in the tuple:

thistuple = (1, 3, 7, 8, 7, 5, 4, 6, 8, 5)

x = thistuple.count(5)

print(x)

```



##### <span style="color:orange">Definition and Usage </span>

The count() method returns the number of times a specified value appears in the tuple.

##### <span style="color:orange">Syntax </span>


tuple.count(value)

##### <span style="color:orange"> Parameter Values</span>


	
$$
\begin{array}{c|c}
\text{Parameter} & \text{Description}  \\ \hline
\text{value} & \text{Required. The item to search for} 
\end{array}
$$
	
#### index()

##### <span style="color:orange"> Python Tuple index() Method  </span>


```{python}
#Example
#Search for the first occurrence of the value 8, and return its position:

thistuple = (1, 3, 7, 8, 7, 5, 4, 6, 8, 5)

x = thistuple.index(8)

print(x)

```


##### <span style="color:orange"> Definition and Usage </span>


The index() method finds the first occurrence of the specified value.

The index() method raises an exception if the value is not found.

##### <span style="color:orange"> Syntax </span>

tuple.index(value)

##### <span style="color:orange"> Parameter Values </span>


$$
\begin{array}{c|c}
\text{Parameter} & \text{Description}  \\ \hline
\text{value} & \text{	Required. The item to search for} 
\end{array}
$$





## Contact us

Contact me at masoudfaridi@modares.ac.ir or masoud1faridi@gmail.com

