---
title: "Python Cheat Sheets-0002-Strings-MasoudF"
output: 
  html_document:
    code_folding: show
    theme:
      bg: "#202123"
      fg: "#B8BCC2"
      primary: "#EA80FC"
      secondary: "#00DAC6"
      base_font:
        google: Prompt
      heading_font:
        google: Proza Libre
---

```{r setup, include=FALSE}
if (requireNamespace("thematic")) 
  thematic::thematic_rmd(font = "auto")
library(reticulate)
reticulate::use_python("C:/Program Files/Python310/python.exe")
```

## <span style="color:orange"> Python Sets  </span> {.tabset .tabset-pills}



```{python}
myset = {"apple", "banana", "cherry"}
print(myset)
```

### Set

Sets are used to store multiple items in a single variable.

Set is one of 4 built-in data types in Python used to store collections of data, the other 3 are List, Tuple, and Dictionary, all with different qualities and usage.

A set is a collection which is unordered, unchangeable*, and unindexed.

<span style="color:yellow">
Note: Set items are unchangeable, but you can remove items and add new items.
</span>


Sets are written with curly brackets.

```{python}
#Example
#Create a Set:

thisset = {"apple", "banana", "cherry"}
print(thisset)

```

<span style="color:yellow">
Note: Sets are unordered, so you cannot be sure in which order the items will appear.  
</span>


#### <span style="color:orange"> Set Items  </span>

Set items are unordered, unchangeable, and do not allow duplicate values.

#### <span style="color:orange">  Unordered </span>

Unordered means that the items in a set do not have a defined order.

Set items can appear in a different order every time you use them, and cannot be referred to by index or key.

#### <span style="color:orange"> Unchangeable  </span>

Set items are unchangeable, meaning that we cannot change the items after the set has been created.

Once a set is created, you cannot change its items, but you can remove items and add new items.

#### <span style="color:orange">  Duplicates Not Allowed </span>

Sets cannot have two items with the same value.

```{python}
#Example
#Duplicate values will be ignored:

thisset = {"apple", "banana", "cherry", "apple"}

print(thisset)

```


#### <span style="color:orange"> Get the Length of a Set  </span>

To determine how many items a set has, use the len() function.

```{python}
#Example
#Get the number of items in a set:

thisset = {"apple", "banana", "cherry"}

print(len(thisset))

```


#### <span style="color:orange">  Set Items - Data Types </span>

Set items can be of any data type:

```{python}
#Example
#String, int and boolean data types:

set1 = {"apple", "banana", "cherry"}
set2 = {1, 5, 7, 9, 3}
set3 = {True, False, False}

```

A set can contain different data types:

```{python}
#Example
#A set with strings, integers and boolean values:

set1 = {"abc", 34, True, 40, "male"}

```


#### <span style="color:orange"> type()  </span>

From Python's perspective, sets are defined as objects with the data type 'set':


<class 'set'>


```{python}
#Example
#What is the data type of a set?

myset = {"apple", "banana", "cherry"}
print(type(myset))

```


#### <span style="color:orange">  The set() Constructor </span>

It is also possible to use the set() constructor to make a set.

```{python}
#Example
#Using the set() constructor to make a set:

thisset = set(("apple", "banana", "cherry")) # note the double round-brackets
print(thisset)
```

#### <span style="color:orange"> Python Collections (Arrays)  </span>

There are four collection data types in the Python programming language:

* List is a collection which is ordered and changeable. Allows duplicate members.
* Tuple is a collection which is ordered and unchangeable. Allows duplicate members.
* Set is a collection which is unordered, unchangeable*, and unindexed. No duplicate members.
* Dictionary is a collection which is ordered** and changeable. No duplicate members.

<span style="color:yellow">
Set items are unchangeable, but you can remove items and add new items.  
</span>


<span style="color:yellow">
As of Python version 3.7, dictionaries are ordered. In Python 3.6 and earlier, dictionaries are unordered.  
</span>


When choosing a collection type, it is useful to understand the properties of that type. Choosing the right type for a particular data set could mean retention of meaning, and, it could mean an increase in efficiency or security.



### Access Set Items

#### <span style="color:orange"> Access Items </span>


You cannot access items in a set by referring to an index or a key.

But you can loop through the set items using a for loop, or ask if a specified value is present in a set, by using the in keyword.


```{python}
#Example
#Loop through the set, and print the values:

thisset = {"apple", "banana", "cherry"}

for x in thisset:
  print(x)

```



```{python}
#Example
#Check if "banana" is present in the set:

thisset = {"apple", "banana", "cherry"}

print("banana" in thisset)

```


#### <span style="color:orange"> Change Items </span>

Once a set is created, you cannot change its items, but you can add new items.




### Add Set Items

#### <span style="color:orange"> Add Items  </span>



Once a set is created, you cannot change its items, but you can add new items.

To add one item to a set use the add() method.

```{python}
#Example
#Add an item to a set, using the add() method:

thisset = {"apple", "banana", "cherry"}

thisset.add("orange")

print(thisset)

```


#### <span style="color:orange"> Add Sets </span>



To add items from another set into the current set, use the update() method.

```{python}
#Example
#Add elements from tropical into thisset:

thisset = {"apple", "banana", "cherry"}
tropical = {"pineapple", "mango", "papaya"}

thisset.update(tropical)

print(thisset)


```

#### <span style="color:orange"> Add Any Iterable </span>



The object in the update() method does not have to be a set, it can be any iterable object (tuples, lists, dictionaries etc.).

```{python}
#Example
#Add elements of a list to at set:

thisset = {"apple", "banana", "cherry"}
mylist = ["kiwi", "orange"]

thisset.update(mylist)

print(thisset)

```




### Remove Set Items

#### <span style="color:orange"> Remove Item  </span>

To remove an item in a set, use the remove(), or the discard() method.

```{python}
#Example
#Remove "banana" by using the remove() method:

thisset = {"apple", "banana", "cherry"}

thisset.remove("banana")

print(thisset)

```

<span style="color:yellow">
Note: If the item to remove does not exist, remove() will raise an error.
</span>


```{python}
#Example
#Remove "banana" by using the discard() method:

thisset = {"apple", "banana", "cherry"}

thisset.discard("banana")

print(thisset)

```


<span style="color:yellow">
Note: If the item to remove does not exist, discard() will NOT raise an error.
</span>


You can also use the pop() method to remove an item, but this method will remove the last item. Remember that sets are unordered, so you will not know what item that gets removed.

The return value of the pop() method is the removed item.

```{python}
#Example
#Remove the last item by using the pop() method:

thisset = {"apple", "banana", "cherry"}

x = thisset.pop()

print(x)

print(thisset)

```


<span style="color:yellow">
Note: Sets are unordered, so when using the pop() method, you do not know which item that gets removed.
</span>


```{python}
#Example
#The clear() method empties the set:

thisset = {"apple", "banana", "cherry"}

thisset.clear()

print(thisset)

```



```{python}
#Example
#The del keyword will delete the set completely:

thisset = {"apple", "banana", "cherry"}

del thisset

#print(thisset) #NameError: name 'thisset' is not defined

```



### Loop Sets

#### <span style="color:orange"> Loop Items </span>



You can loop through the set items by using a for loop:

```{python}
#Example
#Loop through the set, and print the values:

thisset = {"apple", "banana", "cherry"}

for x in thisset:
  print(x)


```




### Join Sets

#### <span style="color:orange"> Join Two Sets </span>

There are several ways to join two or more sets in Python.

You can use the union() method that returns a new set containing all items from both sets, or the update() method that inserts all the items from one set into another:

```{python}
#Example
#The union() method returns a new set with all items from both sets:

set1 = {"a", "b" , "c"}
set2 = {1, 2, 3}

set3 = set1.union(set2)
print(set3)

```

```{python}
#Example
#The update() method inserts the items in set2 into set1:

set1 = {"a", "b" , "c"}
set2 = {1, 2, 3}

set1.update(set2)
print(set1)

```

<span style="color:yellow">
Note: Both union() and update() will exclude any duplicate items.
</span>


#### <span style="color:orange"> Keep ONLY the Duplicates </span>


The intersection_update() method will keep only the items that are present in both sets.

```{python}
#Example
#Keep the items that exist in both set x, and set y:

x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

x.intersection_update(y)

print(x)

```

The intersection() method will return a new set, that only contains the items that are present in both sets.

```{python}
#Example
#Return a set that contains the items that exist in both set x, and set y:

x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

z = x.intersection(y)

print(z)

```


#### <span style="color:orange">  </span>
Keep All, But NOT the Duplicates
The symmetric_difference_update() method will keep only the elements that are NOT present in both sets.

```{python}
#Example
#Keep the items that are not present in both sets:

x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

x.symmetric_difference_update(y)

print(x)

```

The symmetric_difference() method will return a new set, that contains only the elements that are NOT present in both sets.

```{python}
#Example
#Return a set that contains all items from both sets, except items that are present #in both:

x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

z = x.symmetric_difference(y)

print(z)

```








## Contact us

Contact me at masoudfaridi@modares.ac.ir or masoud1faridi@gmail.com

