---
title: "Python Cheat Sheets-0002-Strings-MasoudF"
output: 
  html_document:
    code_folding: show
    theme:
      bg: "#202123"
      fg: "#B8BCC2"
      primary: "#EA80FC"
      secondary: "#00DAC6"
      base_font:
        google: Prompt
      heading_font:
        google: Proza Libre
---

```{r setup, include=FALSE}
if (requireNamespace("thematic")) 
  thematic::thematic_rmd(font = "auto")
library(reticulate)
reticulate::use_python("C:/Program Files/Python310/python.exe")
```

## <span style="color:orange"> Set Methods  </span> {.tabset .tabset-pills}



### Set Methods

Python has a set of built-in methods that you can use on sets.

$$
\begin{array}{c|l}
\text{Method} & \text{	Description}  \\ \hline
\text{add()} & \text{	Adds an element to the set}  \\
\text{clear()} & \text{	Removes all the elements from the set}  \\
\text{copy()} & \text{	Returns a copy of the set}  \\
\text{difference()} & \text{	Returns a set containing the difference between two or more sets}  \\
\text{difference_update()} & \text{	Removes the items in this set that are also included in another, specified set}  \\
\text{discard()} & \text{	Remove the specified item}  \\
\text{intersection()} & \text{	Returns a set, that is the intersection of two other sets}  \\
\text{intersection_update()} & \text{	Removes the items in this set that are not present in other, specified set(s)}  \\
\text{isdisjoint()} & \text{	Returns whether two sets have a intersection or not}  \\
\text{issubset()} & \text{	Returns whether another set contains this set or not}  \\
\text{issuperset()} & \text{	Returns whether this set contains another set or not}  \\
\text{pop()} & \text{	Removes an element from the set}  \\
\text{remove()} & \text{	Removes the specified element}  \\
\text{symmetric_difference()} & \text{	Returns a set with the symmetric differences of two sets}  \\
\text{symmetric_difference_update()} & \text{	inserts the symmetric differences from this set and another}  \\
\text{union()} & \text{	Return a set containing the union of sets}  \\
\text{update()} & \text{	Update the set with the union of this set and others}
\end{array}
$$

### add() 

#### <span style="color:orange"> Python Set add() Method </span>


```{python}
#Example
#Add an element to the fruits set:

fruits = {"apple", "banana", "cherry"}

fruits.add("orange")

print(fruits)

```


#### <span style="color:orange"> Definition and Usage </span>

The add() method adds an element to the set.

If the element already exists, the add() method does not add the element.

#### <span style="color:orange"> Syntax </span>

set.add(elmnt)

#### <span style="color:orange"> Parameter Values </span>


$$
\begin{array}{c|c}
\text{Parameter} & \text{Description}  \\ \hline
\text{elmnt} & \text{	Required. The element to add to the set} 
\end{array}
$$



#### <span style="color:orange"> More Examples </span>


```{python}
#Example
#Try to add an element that already exists:

fruits = {"apple", "banana", "cherry"}

fruits.add("apple")

print(fruits)


```



### clear()

#### <span style="color:orange"> Python Set clear() Method </span>


```{python}
#Example
#Remove all elements from the fruits set:

fruits = {"apple", "banana", "cherry"}

fruits.clear()

print(fruits)

```


#### <span style="color:orange"> Definition and Usage </span>

The clear() method removes all elements in a set.

#### <span style="color:orange">Syntax  </span>

set.clear()

#### <span style="color:orange"> Parameter Values </span>

No parameters




### copy()

#### <span style="color:orange"> Python Set copy() Method </span>


```{python}
#Example
#Copy the fruits set:

fruits = {"apple", "banana", "cherry"}

x = fruits.copy()

print(x)

```


#### <span style="color:orange"> Definition and Usage </span>

The copy() method copies the set.


#### <span style="color:orange"> Syntax </span>

set.copy()

#### <span style="color:orange"> Parameter Values </span>

No parameters



### difference()


#### <span style="color:orange"> Python Set difference() Method </span>


```{python}
#Example
#Return a set that contains the items that only exist in set x, and not in set y:

x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

z = x.difference(y)

print(z)

```


#### <span style="color:orange"> Definition and Usage </span>

The difference() method returns a set that contains the difference between two sets.

Meaning: The returned set contains items that exist only in the first set, and not in both sets.


#### <span style="color:orange"> Syntax </span>

set.difference(set)

#### <span style="color:orange"> Parameter Values </span>


$$
\begin{array}{c|c}
\text{Parameter} & \text{Description}  \\ \hline
\text{set} & \text{Required. The set to check for differences in} 
\end{array}
$$


	

#### <span style="color:orange"> More Examples </span>



```{python}
#Example
#Reverse the first example. Return a set that contains the items that only exist in set y, and not in set x:

x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

z = y.difference(x)

print(z)

```



### difference_update()


#### <span style="color:orange"> Python Set difference_update() Method </span>


```{python}
#Example
#Remove the items that exist in both sets:

x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

x.difference_update(y)

print(x)

```


#### <span style="color:orange">  Definition and Usage </span>

The difference_update() method removes the items that exist in both sets.

The difference_update() method is different from the difference() method, because the difference() method returns a new set, without the unwanted items, and the difference_update() method removes the unwanted items from the original set.


#### <span style="color:orange"> Syntax </span>

set.difference_update(set)

#### <span style="color:orange"> Parameter Values </span>

$$
\begin{array}{c|c}
\text{Parameter} & \text{Description}  \\ \hline
\text{set} & \text{Required. The set to check for differences in} 
\end{array}
$$
	
### discard()

#### <span style="color:orange">Python Set discard() Method  </span>



```{python}
#Example
#Remove "banana" from the set:

fruits = {"apple", "banana", "cherry"}

fruits.discard("banana")

print(fruits)

```


#### <span style="color:orange"> Definition and Usage </span>

The discard() method removes the specified item from the set.

This method is different from the remove() method, because the remove() method will raise an error if the specified item does not exist, and the discard() method will not.


#### <span style="color:orange"> Syntax </span>

set.discard(value)

#### <span style="color:orange"> Parameter Values </span>



$$
\begin{array}{c|c}
\text{Parameter} & \text{Description}  \\ \hline
\text{value} & \text{Required. The item to search for, and remove} 
\end{array}
$$

### intersection()

#### <span style="color:orange">  Python Set intersection() Method</span>



```{python}
#Example
#Return a set that contains the items that exist in both set x, and set y:

x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

z = x.intersection(y)

print(z)

```



#### <span style="color:orange"> Definition and Usage </span>

The intersection() method returns a set that contains the similarity between two or more sets.

Meaning: The returned set contains only items that exist in both sets, or in all sets if the comparison is done with more than two sets.


#### <span style="color:orange"> Syntax </span>

set.intersection(set1, set2 ... etc)

#### <span style="color:orange"> Parameter Values </span>


$$
\begin{array}{c|l}
\text{Parameter} & \text{Description}  \\ \hline
\text{set1} & \text{Required. The set to search for equal items in} \\
\text{set2} & \text{	Optional. The other set to search for equal items in.
You can compare as many sets you like.
Separate the sets with a comma} 
\end{array}
$$

	


#### <span style="color:orange"> More Examples  </span>


```{python}
#Example
#Compare 3 sets, and return a set with items that is present in all 3 sets:

x = {"a", "b", "c"}
y = {"c", "d", "e"}
z = {"f", "g", "c"}

result = x.intersection(y, z)

print(result)


```



### intersection_update()

#### <span style="color:orange"> Python Set intersection_update() Method </span>


```{python}
#Example
#Remove the items that is not present in both x and y:

x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

x.intersection_update(y)

print(x)


```

#### <span style="color:orange"> Definition and Usage </span>

The intersection_update() method removes the items that is not present in both sets (or in all sets if the comparison is done between more than two sets).

The intersection_update() method is different from the intersection() method, because the intersection() method returns a new set, without the unwanted items, and the intersection_update() method removes the unwanted items from the original set.


#### <span style="color:orange"> Syntax </span>

set.intersection_update(set1, set2 ... etc)

#### <span style="color:orange"> Parameter Values </span>

$$
\begin{array}{c|l}
\text{Parameter} & \text{Description}  \\ \hline
\text{set1} & \text{Required. The set to search for equal items in} \\
\text{set2} & \text{Optional. The other set to search for equal items in.
You can compare as many sets you like.
Separate the sets with a comma}
\end{array}
$$


#### <span style="color:orange"> More Examples </span>

```{python}
#Example
#Compare 3 sets, and return a set with items that is present in all 3 sets:

x = {"a", "b", "c"}
y = {"c", "d", "e"}
z = {"f", "g", "c"}

x.intersection_update(y, z)

print(x)

```




### isdisjoint()


#### <span style="color:orange"> Python Set isdisjoint() Method </span>


```{python}
#Example
#Return True if no items in set x is present in set y:

x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "facebook"}

z = x.isdisjoint(y)

print(z)

```


#### <span style="color:orange"> Definition and Usage </span>


The isdisjoint() method returns True if none of the items are present in both sets, otherwise it returns False.


#### <span style="color:orange"> Syntax </span>

set.isdisjoint(set)

#### <span style="color:orange">  Parameter Values</span>


$$
\begin{array}{c|l}
\text{Parameter} & \text{Description}  \\ \hline
\text{set} & \text{Required. The set to search for equal items in} 
\end{array}
$$
	

#### <span style="color:orange">More Examples  </span>

```{python}
#Example
#What if no items are present in both sets?

#Return False if one ore more items are present in both sets:

x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

z = x.isdisjoint(y)

print(z)

```


###  issubset()



#### <span style="color:orange"> Python Set issubset() Method </span>



```{python}
#Example
#Return True if all items in set x are present in set y:

x = {"a", "b", "c"}
y = {"f", "e", "d", "c", "b", "a"}

z = x.issubset(y)

print(z)

```


#### <span style="color:orange"> Definition and Usage </span>

The issubset() method returns True if all items in the set exists in the specified set, otherwise it retuns False.


#### <span style="color:orange"> Syntax</span>

set.issubset(set)

#### <span style="color:orange"> Parameter Values </span>

$$
\begin{array}{c|l}
\text{Parameter} & \text{Description}  \\ \hline
\text{set} & \text{Required. The set to search for equal items in} 
\end{array}
$$
	

#### <span style="color:orange"> More Examples </span>

```{python}
#Example
#What if not all items are present in the specified set?

#Return False if not all items in set x are present in set y:

x = {"a", "b", "c"}
y = {"f", "e", "d", "c", "b"}

z = x.issubset(y)

print(z)

```

	
### issuperset()


#### <span style="color:orange"> Python Set issuperset() Method </span>


```{python}
#Example
#Return True if all items set y are present in set x:

x = {"f", "e", "d", "c", "b", "a"}
y = {"a", "b", "c"}

z = x.issuperset(y)

print(z)

```


#### <span style="color:orange"> Definition and Usage </span>

The issuperset() method returns True if all items in the specified set exists in the original set, otherwise it retuns False.


#### <span style="color:orange"> Syntax </span>

set.issuperset(set)

#### <span style="color:orange"> Parameter Values </span>


$$
\begin{array}{c|l}
\text{Parameter} & \text{Description}  \\ \hline
\text{set} & \text{	Required. The set to search for equal items in} 
\end{array}
$$

#### <span style="color:orange"> More Examples </span>

```{python}
#Example
#What if not all items are present in the specified set?

#Return False if not all items in set y are present in set x:

x = {"f", "e", "d", "c", "b"}
y = {"a", "b", "c"}

z = x.issuperset(y)

print(z)

```



### pop()


#### <span style="color:orange"> Python Set pop() Method </span>


```{python}
#Example
#Remove a random item from the set:

fruits = {"apple", "banana", "cherry"}

fruits.pop()

print(fruits)

```


#### <span style="color:orange">  Definition and Usage</span>

The pop() method removes a random item from the set.

This method returns the removed item.


#### <span style="color:orange"> Syntax </span>

set.pop()

#### <span style="color:orange"> Parameter Values </span>

No parameter values.


#### <span style="color:orange"> More Examples </span>

```{python}
#Example
#Return the removed element:

fruits = {"apple", "banana", "cherry"}

x = fruits.pop()

print(x)

```


<span style="color:yellow">
Note: The pop() method returns removed value.
</span>


### remove()

#### <span style="color:orange"> Python Set remove() Method </span>


```{python}
#Example
#Remove "banana" from the set:

fruits = {"apple", "banana", "cherry"}

fruits.remove("banana")

print(fruits)

```


#### <span style="color:orange"> Definition and Usage </span>

The remove() method removes the specified element from the set.

This method is different from the discard() method, because the remove() method will raise an error if the specified item does not exist, and the discard() method will not.

#### <span style="color:orange"> Syntax </span>

set.remove(item)

#### <span style="color:orange">Parameter Values </span>




$$
\begin{array}{c|l}
\text{Parameter} & \text{Description}  \\ \hline
\text{item} & \text{	Required. The item to search for, and remove} 
\end{array}
$$


### symmetric_difference()


#### <span style="color:orange"> Python Set symmetric_difference() Method </span>


```{python}
#Example
#Return a set that contains all items from both sets, except items that are present in both sets:

x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

z = x.symmetric_difference(y)

print(z)

```


#### <span style="color:orange"> Definition and Usage </span>

The symmetric_difference() method returns a set that contains all items from both set, but not the items that are present in both sets.

Meaning: The returned set contains a mix of items that are not present in both sets.


#### <span style="color:orange"> Syntax </span>

set.symmetric_difference(set)

#### <span style="color:orange"> Parameter Values </span>



$$
\begin{array}{c|l}
\text{Parameter} & \text{Description}  \\ \hline
\text{set} & \text{Required. The set to check for matches in} 
\end{array}
$$

### symmetric_difference_update()


#### <span style="color:orange"> Python Set symmetric_difference_update() Method </span>


```{python}
#Example
#Remove the items that are present in both sets, AND insert the items that is not present in both sets:

x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

x.symmetric_difference_update(y)

print(x)

```


#### <span style="color:orange">  Definition and Usage</span>

The symmetric_difference_update() method updates the original set by removing items that are present in both sets, and inserting the other items.

#### <span style="color:orange"> Syntax </span>

set.symmetric_difference_update(set)

#### <span style="color:orange"> Parameter Values </span>


	
$$
\begin{array}{c|l}
\text{Parameter} & \text{Description}  \\ \hline
\text{set} & \text{Required. The set to check for matches in} 
\end{array}
$$



### union()

#### <span style="color:orange"> Python Set union() Method </span>


```{python}
#Example
#Return a set that contains all items from both sets, duplicates are excluded:

x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

z = x.union(y)

print(z)

```


#### <span style="color:orange"> Definition and Usage </span>

The union() method returns a set that contains all items from the original set, and all items from the specified set(s).

You can specify as many sets you want, separated by commas.

It does not have to be a set, it can be any iterable object.

If an item is present in more than one set, the result will contain only one appearance of this item.


#### <span style="color:orange"> Syntax </span>

set.union(set1, set2...)

#### <span style="color:orange"> Parameter Values </span>


	
	

$$
\begin{array}{c|l}
\text{Parameter} & \text{Description}  \\ \hline
\text{set1} & \text{Required. The iterable to unify with} \\
\text{set2} & \text{Optional. The other iterable to unify with.
You can compare as many iterables as you like.
Separate each iterable with a comma} 
\end{array}
$$


#### <span style="color:orange"> More Examples </span>


```{python}
#Example
#Unify more than 2 sets:

x = {"a", "b", "c"}
y = {"f", "d", "a"}
z = {"c", "d", "e"}

result = x.union(y, z)

print(result)
```





### update()


#### <span style="color:orange"> Python Set update() Method </span>


```{python}
#Example
#Insert the items from set y into set x:

x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

x.update(y)

print(x)

```


#### <span style="color:orange"> Definition and Usage </span>

The update() method updates the current set, by adding items from another set (or any other iterable).

If an item is present in both sets, only one appearance of this item will be present in the updated set.


#### <span style="color:orange"> Syntax </span>

set.update(set)

#### <span style="color:orange">  Parameter Values</span>


	

$$
\begin{array}{c|l}
\text{Parameter} & \text{Description}  \\ \hline
\text{set} & \text{Required. The iterable insert into the current set} 
\end{array}
$$





## Contact us

Contact me at masoudfaridi@modares.ac.ir or masoud1faridi@gmail.com

