---
title: "Python Cheat Sheets-0002-Strings-MasoudF"
output: 
  html_document:
    code_folding: show
    theme:
      bg: "#202123"
      fg: "#B8BCC2"
      primary: "#EA80FC"
      secondary: "#00DAC6"
      base_font:
        google: Prompt
      heading_font:
        google: Proza Libre
---

```{r setup, include=FALSE}
if (requireNamespace("thematic")) 
  thematic::thematic_rmd(font = "auto")
library(reticulate)
reticulate::use_python("C:/Program Files/Python310/python.exe")
```

## <span style="color:orange"> Python Dictionaries  </span> {.tabset .tabset-pills}


### Dictionary


```{python}
#Example
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

print(thisdict)
```


Dictionaries are used to store data values in key:value pairs.

A dictionary is a collection which is ordered*, changeable and do not allow duplicates.

<span style="color:yellow">
As of Python version 3.7, dictionaries are ordered. In Python 3.6 and earlier, dictionaries are unordered.
</span>


Dictionaries are written with curly brackets, and have keys and values:

```{python}
#Example
#Create and print a dictionary:

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict)

```


#### <span style="color:orange"> Dictionary Items </span>

Dictionary items are ordered, changeable, and does not allow duplicates.

Dictionary items are presented in key:value pairs, and can be referred to by using the key name.

```{python}
#Example
#Print the "brand" value of the dictionary:

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict["brand"])

```


#### <span style="color:orange"> Ordered or Unordered? </span>

<span style="color:yellow">
As of Python version 3.7, dictionaries are ordered. In Python 3.6 and earlier, dictionaries are unordered.
</span>


When we say that dictionaries are ordered, it means that the items have a defined order, and that order will not change.

Unordered means that the items does not have a defined order, you cannot refer to an item by using an index.


#### <span style="color:orange"> Changeable </span>

Dictionaries are changeable, meaning that we can change, add or remove items after the dictionary has been created.


#### <span style="color:orange"> Duplicates Not Allowed </span>

Dictionaries cannot have two items with the same key:

```{python}
#Example
#Duplicate values will overwrite existing values:

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964,
  "year": 2020
}
print(thisdict)


```


#### <span style="color:orange"> Dictionary Length </span>


To determine how many items a dictionary has, use the len() function:

```{python}
#Example
#Print the number of items in the dictionary:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964,
  "year": 2020
}
print(len(thisdict))

```


#### <span style="color:orange"> Dictionary Items - Data Types </span>

The values in dictionary items can be of any data type:

```{python}
#Example
#String, int, boolean, and list data types:

thisdict = {
  "brand": "Ford",
  "electric": False,
  "year": 1964,
  "colors": ["red", "white", "blue"]
}

```


#### <span style="color:orange"> type() </span>

From Python's perspective, dictionaries are defined as objects with the data type 'dict':

<class 'dict'>

```{python}
#Example
#Print the data type of a dictionary:

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(type(thisdict))

```


#### <span style="color:orange"> Python Collections (Arrays) </span>

There are four collection data types in the Python programming language:

* List is a collection which is ordered and changeable. Allows duplicate members.
* Tuple is a collection which is ordered and unchangeable. Allows duplicate members.
* Set is a collection which is unordered, unchangeable*, and unindexed. No duplicate members.
* Dictionary is a collection which is ordered** and changeable. No duplicate members.

<span style="color:yellow">
Set items are unchangeable, but you can remove and/or add items whenever you like.
</span>


<span style="color:yellow">
As of Python version 3.7, dictionaries are ordered. In Python 3.6 and earlier, dictionaries are unordered.
</span>


When choosing a collection type, it is useful to understand the properties of that type. Choosing the right type for a particular data set could mean retention of meaning, and, it could mean an increase in efficiency or security.







### Accessing Items

#### <span style="color:orange"> Python - Access Dictionary Items  </span>

You can access the items of a dictionary by referring to its key name, inside square brackets:

```{python}
#Example
#Get the value of the "model" key:

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
x = thisdict["model"]

```

There is also a method called get() that will give you the same result:

```{python}
#Example
#Get the value of the "model" key:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
x = thisdict.get("model")

```


#### <span style="color:orange">  Get Keys </span>

The keys() method will return a list of all the keys in the dictionary.

```{python}
#Example
#Get a list of the keys:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
x = thisdict.keys()

```

The list of the keys is a view of the dictionary, meaning that any changes done to the dictionary will be reflected in the keys list.

```{python}
#Example
#Add a new item to the original dictionary, and see that the keys list gets updated as well:

car = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}

x = car.keys()

print(x) #before the change

car["color"] = "white"

print(x) #after the change

```



#### <span style="color:orange"> Get Values  </span>


The values() method will return a list of all the values in the dictionary.

```{python}
#Example
#Get a list of the values:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
x = thisdict.values()

```

The list of the values is a view of the dictionary, meaning that any changes done to the dictionary will be reflected in the values list.

```{python}
#Example
car = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}

x = car.values()

print(x) #before the change

car["year"] = 2020

print(x) #after the change

```
Make a change in the original dictionary, and see that the values list gets updated as well:


```{python}
#Example
#Add a new item to the original dictionary, and see that the values list gets updated as well:

car = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}

x = car.values()

print(x) #before the change

car["color"] = "red"

print(x) #after the change

```


#### <span style="color:orange"> Get Items  </span>

The items() method will return each item in a dictionary, as tuples in a list.

```{python}
#Example
#Get a list of the key:value pairs

x = thisdict.items()

```

The returned list is a view of the items of the dictionary, meaning that any changes done to the dictionary will be reflected in the items list.

```{python}
#Example
car = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}

x = car.items()

print(x) #before the change
car["year"] = 2020

print(x) #after the change

```
Make a change in the original dictionary, and see that the items list gets updated as well:




```{python}
#Example
#Add a new item to the original dictionary, and see that the items list gets updated as well:

car = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}

x = car.items()

print(x) #before the change

car["color"] = "red"

print(x) #after the change

```


#### <span style="color:orange">  Check if Key Exists </span>

To determine if a specified key is present in a dictionary use the in keyword:

```{python}
#Example
#Check if "model" is present in the dictionary:

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
if "model" in thisdict:
  print("Yes, 'model' is one of the keys in the thisdict dictionary")


```






### Change Values 

#### <span style="color:orange"> Python - Change Dictionary Items </span>

You can change the value of a specific item by referring to its key name:

```{python}
#Example
#Change the "year" to 2018:

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict["year"] = 2018
print(thisdict)

```


#### <span style="color:orange"> Update Dictionary </span>

The update() method will update the dictionary with the items from the given argument.

The argument must be a dictionary, or an iterable object with key:value pairs.

```{python}
#Example
#Update the "year" of the car by using the update() method:

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict.update({"year": 2020})
print(thisdict)
```



### Adding Items 


#### <span style="color:orange"> Python - Add Dictionary Items </span>

Adding an item to the dictionary is done by using a new index key and assigning a value to it:

```{python}
#Example
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict["color"] = "red"
print(thisdict)

```


#### <span style="color:orange"> Update Dictionary </span>

The update() method will update the dictionary with the items from a given argument. If the item does not exist, the item will be added.

The argument must be a dictionary, or an iterable object with key:value pairs.

```{python}
#Example
#Add a color item to the dictionary by using the update() method:

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict.update({"color": "red"})

```




### Removing Items 

#### <span style="color:orange"> Python - Remove Dictionary Items </span>

There are several methods to remove items from a dictionary:


```{python}
#Example
#The pop() method removes the item with the specified key name:

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict.pop("model")
print(thisdict)


```

```{python}
#Example
#The popitem() method removes the last inserted item (in versions before 3.7, a random item is removed instead):

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict.popitem()
print(thisdict)

```


```{python}
#Example
#The del keyword removes the item with the specified key name:

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
del thisdict["model"]
print(thisdict)

```


```{python}
#Example
#The del keyword can also delete the dictionary completely:

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
del thisdict
#print(thisdict) #this will cause an error because "thisdict" no longer exists.

```


```{python}
#Example
#The clear() method empties the dictionary:

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict.clear()
print(thisdict)

```





### Loop Dictionaries

#### <span style="color:orange"> Loop Through a Dictionary </span>

You can loop through a dictionary by using a for loop.

When looping through a dictionary, the return value are the keys of the dictionary, but there are methods to return the values as well.

```{python}
#Example
#Print all key names in the dictionary, one by one:

for x in thisdict:
  print(x)

```


```{python}
#Example
#Print all values in the dictionary, one by one:

for x in thisdict:
  print(thisdict[x])

```


```{python}
#Example
#You can also use the values() method to return values of a dictionary:

for x in thisdict.values():
  print(x)

```


```{python}
#Example
#You can use the keys() method to return the keys of a dictionary:

for x in thisdict.keys():
  print(x)

```


```{python}
#Example
#Loop through both keys and values, by using the items() method:

for x, y in thisdict.items():
  print(x, y)

```




### Copy()

#### <span style="color:orange"> Python - Copy Dictionaries </span>

You cannot copy a dictionary simply by typing dict2 = dict1, because: dict2 will only be a reference to dict1, and changes made in dict1 will automatically also be made in dict2.

There are ways to make a copy, one way is to use the built-in Dictionary method copy().

```{python}
#Example
#Make a copy of a dictionary with the copy() method:

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
mydict = thisdict.copy()
print(mydict)

```

Another way to make a copy is to use the built-in function dict().

```{python}
#Example
#Make a copy of a dictionary with the dict() function:

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
mydict = dict(thisdict)
print(mydict)

```




### Nested Dictionaries 


#### <span style="color:orange"> Python - Nested Dictionaries </span>

A dictionary can contain dictionaries, this is called nested dictionaries.

```{python}
#Example
#Create a dictionary that contain three dictionaries:

myfamily = {
  "child1" : {
    "name" : "Emil",
    "year" : 2004
  },
  "child2" : {
    "name" : "Tobias",
    "year" : 2007
  },
  "child3" : {
    "name" : "Linus",
    "year" : 2011
  }
}

```

Or, if you want to add three dictionaries into a new dictionary:

```{python}
#Example
#Create three dictionaries, then create one dictionary that will contain the other three dictionaries:

child1 = {
  "name" : "Emil",
  "year" : 2004
}
child2 = {
  "name" : "Tobias",
  "year" : 2007
}
child3 = {
  "name" : "Linus",
  "year" : 2011
}

myfamily = {
  "child1" : child1,
  "child2" : child2,
  "child3" : child3
}

```





## Contact us

Contact me at masoudfaridi@modares.ac.ir or masoud1faridi@gmail.com

