---
title: "Python Cheat Sheets-0002-Strings-MasoudF"
output: 
  html_document:
    code_folding: show
    theme:
      bg: "#202123"
      fg: "#B8BCC2"
      primary: "#EA80FC"
      secondary: "#00DAC6"
      base_font:
        google: Prompt
      heading_font:
        google: Proza Libre
---

```{r setup, include=FALSE}
if (requireNamespace("thematic")) 
  thematic::thematic_rmd(font = "auto")
library(reticulate)
reticulate::use_python("C:/Program Files/Python310/python.exe")
```

 

## <span style="color:red"> Other Methods </span> {.tabset .tabset-pills}


### Booleans

#### <span style="color:orange"> Python Booleans </span>


Booleans represent one of two values: True or False.

#### Boolean Values

In programming you often need to know if an expression is True or False.

You can evaluate any expression in Python, and get one of two answers, True or False.

When you compare two values, the expression is evaluated and Python returns the Boolean answer:

Example

```{python}
print(10 > 9)
print(10 == 9)
print(10 < 9)
```

When you run a condition in an if statement, Python returns True or False:

Example

Print a message based on whether the condition is True or False:

```{python}
a = 200
b = 33

if b > a:
  print("b is greater than a")
else:
  print("b is not greater than a")
```

#### Evaluate Values and Variables

The bool() function allows you to evaluate any value, and give you True or False in return,

Example

Evaluate a string and a number:

```{python}
print(bool("Hello"))
print(bool(15))
```

Example

Evaluate two variables:

```{python}
x = "Hello"
print(bool(x))
y = 15
print(bool(y))
```
ADVERTISEMENT

#### Most Values are True

Almost any value is evaluated to True if it has some sort of content.

Any string is True, except empty strings.

Any number is True, except 0.

Any list, tuple, set, and dictionary are True, except empty ones.

Example

The following will return True:

```{python}
bool("abc")
bool(123)
bool(["apple", "cherry", "banana"])
```

#### Some Values are False

In fact, there are not many values that evaluate to False, except empty values, such as (), [], {}, "", the number 0, and the value None. And of course the value False evaluates to False.

Example
The following will return False:

```{python}
bool(False)
bool(None)
bool(0)
bool("")
bool(())
bool([])
bool({})
```

One more value, or object in this case, evaluates to False, and that is if you have an object that is made from a class with a __len__ function that returns 0 or False:

Example

```{python}
class myclass():
  def __len__(self):
    return 0

myobj = myclass()
print(bool(myobj))
```

#### Functions can Return a Boolean

You can create functions that returns a Boolean Value:

Example

Print the answer of a function:

```{python}
def myFunction() :
  return True

print(myFunction())
```

You can execute code based on the Boolean answer of a function:

Example

Print "YES!" if the function returns True, otherwise print "NO!":

```{python}
def myFunction() :
  return True

if myFunction():
  print("YES!")
else:
  print("NO!")
```

Python also has many built-in functions that return a boolean value, like the isinstance() function, which can be used to determine if an object is of a certain data type:

Example
Check if an object is an integer or not:
```{python}
x = 200
print(isinstance(x, int))
```


### Python Operators {.tabset .tabset-pills}

#### <span style="color:orange"> Python Operators </span>



Operators are used to perform operations on variables and values.

In the example below, we use the + operator to add together two values:

Example

```{python}
print(10 + 5)
```

Python divides the operators in the following groups:

* Arithmetic operators
* Assignment operators
* Comparison operators
* Logical operators
* Identity operators
* Membership operators
* Bitwise operators

#### Python Arithmetic Operators

Arithmetic operators are used with numeric values to perform common mathematical operations:

$$
\begin{array}{ccc}
\text{ Operator} & 	\text{Name} &	\text{Example} \\ \hline	
\text{+	}& 	\text{Addition} &	\text{	x + y	} \\
\text{-	}& 	\text{Subtraction} &	\text{	x - y	} \\
\text{*	}& 	\text{Multiplication} &	\text{	x * y} \\	
\text{/} & 	\text{	Division} &	\text{	x / y	} \\
\text{%} & 	\text{Modulus} &	\text{	x % y	} \\
\text{**}& 	\text{Exponentiation} &	\text{	x ** y} \\	
\text{//}& 	\text{	Floor division} &	\text{	x // y} \\
\end{array}
$$


```{python}
x = 2
y = 5
print(x ** y) #same as 2*2*2*2*2
x = 15
y = 2
print(x // y)
#the floor division // rounds the result down to the nearest whole number
x = 5
y = 2
print(x % y)
```



#### Python Assignment Operators

Assignment operators are used to assign values to variables:

$$
\begin{array}{ccc}
\text{ Operator}   & 	\text{Example}   & 	\text{Same As} \\ \hline
\text{ =}   & 	\text{	x = 5}   & 	\text{	x = 5	} \\
\text{ +=}   & 	\text{	x += 3}   & 	\text{	x = x + 3	} \\
\text{ -=}   & 	\text{	x -= 3}   & 	\text{	x = x - 3	} \\
\text{ *=}   & 	\text{	x *= 3}   & 	\text{	x = x * 3	} \\
\text{ /=}   & 	\text{	x /= 3}   & 	\text{	x = x / 3	} \\
\text{ %=}   & 	\text{	x %= 3}   & 	\text{	x = x % 3	} \\
\text{ //=}   & 	\text{	x //= 3}   & 	\text{	x = x // 3	} \\
\text{ **=}   & 	\text{	x **= 3}   & 	\text{	x = x ** 3	} \\
\text{ &=}   & 	\text{	x &= 3}   & 	\text{	x = x & 3	} \\
\text{ |=}   & 	\text{	x |= 3}   & 	\text{	x = x | 3	} \\
\text{ ^=}   & 	\text{	x ^= 3}   & 	\text{	x = x ^ 3	} \\
\text{ >>=}   & 	\text{	x >>= 3}   & 	\text{	x = x >> 3	} \\
\text{ <<=}   & 	\text{	x <<= 3}   & 	\text{	x = x << 3	} 
\end{array}
$$

```{python}
x = 5
x+=3
print(x) 

x = 5
x-=3
print(x)

x = 5
x*=3
print(x)

x = 6
x/=2
print(x)


x = 5
x%=2
print(x)

x = 5
x//=2
print(x)


x = 2
x**=3
print(x)


x &= 3 # same as x = x & 3
print(x)
txt3 = "{digit}_binary={digit:6b}"
print(txt3.format(digit=3))
print(txt3.format(digit=5))
print(3 & 5)
print(3 | 5)
print(txt3.format(digit=7))
x = 5
x ^= 3
# ^	XOR	Sets each bit to 1 if only one of two bits is 1
print(x)

x = 5
x >>= 3
#Signed right shift	Shift right by pushing copies of the leftmost bit in from the left, #and let the rightmost bits fall off
print(x)

x = 5
x <<= 3
#<<	Zero fill left shift	Shift left by pushing zeros in from the right and let the #leftmost bits fall off
print(x)

```


#### Python Comparison Operators

Comparison operators are used to compare two values:

$$
\begin{array}{ccc}
\text{ Operator} & 	\text{Name} &	\text{Example} \\ \hline	
\text{==} & 	\text{	Equal} &	\text{	x == y	} \\
\text{!=} & 	\text{	Not equal} &	\text{	x != y	} \\
\text{>} & 	\text{	Greater than} &	\text{	x > y	} \\
\text{<} & 	\text{	Less than	} &	\text{x < y	} \\
\text{>=} & 	\text{	Greater than or equal to} &	\text{	x >= y	} \\
\text{<=} & 	\text{	Less than or equal to} &	\text{	x <= y	} \\
\end{array}
$$
```{python}

x = 5
y = 3
print(x == y)

x = 5
y = 3
print(x != y)


x = 5
y = 3
print(y < x)

x = 5
y = 5
print(y <= x)

```



#### Python Logical Operators

Logical operators are used to combine conditional statements:

$$
\begin{array}{c|c|c}
\text{ Operator} & 	\text{Description} &	\text{Example} \\ \hline
\text{and} & 	\text{ 	Returns True if both statements are true} &	\text{	x < 5 and  x < 10	} \\ 
\text{or} & 	\text{	Returns True if one of the statements is true} &	\text{	x < 5 or x < 4} \\	 
\text{not} & 	\text{	Reverse the result, returns False if the result is true} &	\text{	not(x < 5 and x < 10)	} 
\end{array}
$$
```{python}

x = 5
print(x > 3 and x < 10)
# returns True because 5 is greater than 3 AND 5 is less than 10

x = 5

print(x > 3 or x < 4)

# returns True because one of the conditions are true (5 is greater than 3, but 5 is not #less than 4)

x = 5

print(not(x > 3 and x < 10))

# returns False because not is used to reverse the result

```



#### Python Identity Operators

Identity operators are used to compare the objects, not if they are equal, but if they are actually the same object, with the same memory location:

$$
\begin{array}{c|c|c}
\text{ Operator} & 	\text{Description} &	\text{Example} \\ \hline
\text{ is} & 	\text{ 	Returns True if both variables are the same object} &	\text{	x is y} \\ 	
\text{ is not} & 	\text{	Returns True if both variables are not the same object} &	\text{	x is not y	} \\ 
\end{array}
$$

```{python}
x = ["apple", "banana"]
y = ["apple", "banana"]
z = x

print(x is z)
# returns True because z is the same object as x
x = ["apple", "banana"]
y = ["apple", "banana"]
z = x
print(x is y)
# returns False because x is not the same object as y, even if they have the same content
x = ["apple", "banana"]
y = ["apple", "banana"]
z = x
print(x == y)
# to demonstrate the difference betweeen "is" and "==": this comparison returns True #because x is equal to y


```{python}

x = ["apple", "banana"]
y = ["apple", "banana"]
z = x

print(x is not z)

# returns False because z is the same object as x
x = ["apple", "banana"]
y = ["apple", "banana"]
z = x
print(x is not y)

# returns True because x is not the same object as y, even if they have the same content
x = ["apple", "banana"]
y = ["apple", "banana"]
z = x
print(x != y)

# to demonstrate the difference betweeen "is not" and "!=": this comparison returns False #because x is equal to y

```









#### Python Membership Operators

Membership operators are used to test if a sequence is presented in an object:

$$
\begin{array}{c|c|c}
\text{ Operator} & 	\text{Description} &	\text{Example} \\ \hline
\text{in} & 	\text{ 	Returns True if a sequence with the specified value is present in the object} &	\text{	x in y	} \\ 
\text{not in} & 	\text{	Returns True if a sequence with the specified value is not present in the object} &	\text{	x not in y	}  
\end{array}
$$


```{python}
x = ["apple", "banana"]

print("banana" in x)

# returns True because a sequence with the value "banana" is in the list
```


```{python}
x = ["apple", "banana"]

print("pineapple" not in x)

# returns True because a sequence with the value "pineapple" is not in the list
```


#### Python Bitwise Operators

Bitwise operators are used to compare (binary) numbers:

$$
\begin{array}{c|c|c}
\text{ Operator} & 	\text{Name} &	\text{Description} \\ \hline
\text{&} & 	\text{AND} & 	\text{Sets each bit to 1 if both bits are 1} \\
\text{|} & 	\text{OR} & 	\text{	Sets each bit to 1 if one of two bits is 1} \\
\text{ ^} & 	\text{XOR} & 	\text{Sets each bit to 1 if only one of two bits is 1} \\
\text{~} & 	\text{NOT} & 	\text{Inverts all the bits} \\
\text{<<} & 	\text{Zero fill left shift} & 	\text{Shift left by pushing zeros in from the right and let the leftmost bits fall off} \\
\text{>>} & 	\text{Signed right shift} & 	\text{Shift right by pushing copies of the leftmost bit in from the left, and let the rightmost bits fall off} \\
\end{array}
$$


```{python}
txt3 = "{digit}_binary={digit:6b}"
print(txt3.format(digit=3))
print(txt3.format(digit=5))
print(3 & 5)
#Sets each bit to 1 if both bits are 1
print(3 | 5)
#Sets each bit to 1 if one of two bits is 1
print(txt3.format(digit=7))


print(3 ^ 5)
#Sets each bit to 1 if one of two bits is 1
print(txt3.format(digit=6))
```


```{python}
bin(5)
bin(-6)
print(~5)
#Sets each bit to 1 if one of two bits is 1
print(txt3.format(digit=-6))

-1 == ~0
bin(0)
bin(-1)

print(~1)


bin(10)
bin(-11)

print(~10)


# Print bitwise NOT operation
a=3
print("~a =", ~a)

# 60 = 0011 1100 
a=60
# -61 = 1100 0011
print("~a =", ~a)
```


Example 1:
a = 5 = 0000 0101 (Binary)
a << 1 = 0000 1010 = 10
a << 2 = 0001 0100 = 20 

Example 2:
b = -10 = 1111 0110 (Binary)
b << 1 = 1110 1100 = -20
b << 2 = 1101 1000 = -40 

```{python}
# shift operators
 
a = 10
# print bitwise right shift operator
print("a >> 1 =", a >> 1)
b = -10
print("b >> 1 =", b >> 1)

a = 5
# print bitwise left shift operator
print("a << 1 =", a << 1)
b = -10
print("b << 1 =", b << 1)
```






## Contact us

Contact me at masoudfaridi@modares.ac.ir or masoud1faridi@gmail.com

