---
title: "Python Cheat Sheets-0002-Strings-MasoudF"
output: 
  html_document:
    code_folding: show
    theme:
      bg: "#202123"
      fg: "#B8BCC2"
      primary: "#EA80FC"
      secondary: "#00DAC6"
      base_font:
        google: Prompt
      heading_font:
        google: Proza Libre
---

```{r setup, include=FALSE}
if (requireNamespace("thematic")) 
  thematic::thematic_rmd(font = "auto")
library(reticulate)
reticulate::use_python("C:/Program Files/Python310/python.exe")
```

 

## <span style="color:orange">  List Methodss </span> {.tabset .tabset-pills}

List Methods
Python has a set of built-in methods that you can use on lists.

$$
\begin{array}{cc}
\text{Method} & \text{	Description}  \\ \hline
\text{append()} & \text{	Adds an element at the end of the list} \\
\text{clear()} & \text{	Removes all the elements from the list} \\
\text{copy()} & \text{	Returns a copy of the list} \\
\text{count()} & \text{	Returns the number of elements with the specified value} \\
\text{extend()} & \text{	Add the elements of a list (or any iterable), to the end of the current list} \\
\text{index()} & \text{	Returns the index of the first element with the specified value} \\
\text{insert()} & \text{	Adds an element at the specified position} \\
\text{pop()} & \text{	Removes the element at the specified position} \\
\text{remove()} & \text{	Removes the item with the specified value} \\
\text{reverse()} & \text{	Reverses the order of the list} \\
\text{sort()} & \text{	Sorts the list}
\end{array}
$$

### append() 


```{python}
#Example
#Add an element to the fruits list:

fruits = ['apple', 'banana', 'cherry']
fruits.append("orange")
print(fruits)

```
#### <span style="color:orange"> Definition and Usage </span>

The append() method appends an element to the end of the list.

#### <span style="color:orange"> Syntax </span>

list.append(elmnt)

#### <span style="color:orange"> Parameter Values </span>

$$
\begin{array}{c|c}
\text{Parameter Values} & \text{Parameter	Description}  \\ \hline
\text{elmnt} & \text{Required. An element of any type (string, number, object etc.)} 
\end{array}
$$


	
#### <span style="color:orange"> More Examples </span>


```{python}
#Example
#Add a list to a list:

a = ["apple", "banana", "cherry"]
b = ["Ford", "BMW", "Volvo"]
a.append(b)
print(a)
```


###  clear() 


Remove all elements from the fruits list:

```{python}
fruits = ['apple', 'banana', 'cherry', 'orange']

fruits.clear()
print(fruits)
```

#### <span style="color:orange"> Definition and Usage </span>

The clear() method removes all the elements from a list.

#### <span style="color:orange"> Syntax </span>

list.clear()

#### <span style="color:orange"> Parameter Values </span>

No parameters


### copy() 


```{python}
#Example
#Copy the fruits list:

fruits = ['apple', 'banana', 'cherry', 'orange']

x = fruits.copy()
print(x)
```

#### <span style="color:orange"> Definition and Usage </span>

The copy() method returns a copy of the specified list.

#### <span style="color:orange"> Syntax </span>

list.copy()
#### <span style="color:orange"> Parameter Values </span>

No parameters


### count()




```{python}
#Example
#Return the number of times the value "cherry" appears in the fruits list:

fruits = ['apple', 'banana', 'cherry']

x = fruits.count("cherry")
print(x)
```

#### <span style="color:orange"> Definition and Usage  </span>

The count() method returns the number of elements with the specified value.

#### <span style="color:orange"> Syntax </span>

list.count(value)

#### <span style="color:orange"> Parameter Values </span>

$$
\begin{array}{c|c}
\text{Parameter} & \text{Description}  \\ \hline
\text{value} & \text{Required. Any type (string, number, list, tuple, etc.). The value to search for.} 
\end{array}
$$
	
	
#### <span style="color:orange"> More Examples </span>

```{python}
#Example
#Return the number of times the value 9 appears int the list:

points = [1, 4, 2, 9, 7, 8, 9, 3, 1]

x = points.count(9)
print(x)
```




### extend()


```{python}
#Example
#Add the elements of cars to the fruits list:

fruits = ['apple', 'banana', 'cherry']

cars = ['Ford', 'BMW', 'Volvo']

fruits.extend(cars)
print(fruits)

```


#### <span style="color:orange"> Definition and Usage </span>

The extend() method adds the specified list elements (or any iterable) to the end of the current list.

#### <span style="color:orange"> Syntax </span>

list.extend(iterable)

#### <span style="color:orange"> Parameter Values </span>

$$
\begin{array}{c|c}
\text{Parameter} & \text{Description}  \\ \hline
\text{iterable} & \text{Required. Any iterable (list, set, tuple, etc.)} 
\end{array}
$$
	
	

#### <span style="color:orange"> More Examples </span>



```{python}
#Example
#Add a tuple to the fruits list:

fruits = ['apple', 'banana', 'cherry']

points = (1, 4, 5, 9)

fruits.extend(points)
print(fruits)
```


### index()


```{python}
#Example
#What is the position of the value "cherry":

fruits = ['apple', 'banana', 'cherry']

x = fruits.index("cherry")
print(x)
```

#### <span style="color:orange"> Definition and Usage </span>

The index() method returns the position at the first occurrence of the specified value.

#### <span style="color:orange"> Syntax </span>

list.index(elmnt)

#### <span style="color:orange"> Parameter Values </span>

$$
\begin{array}{c|c}
\text{Parameter} & \text{Description}  \\ \hline
\text{elmnt} & \text{Required. Any type (string, number, list, etc.). The element to search for.} 
\end{array}
$$

	

#### <span style="color:orange"> More Examples  </span> 


```{python}
#Example
#What is the position of the value 32:

fruits = [4, 55, 64, 32, 16, 32]

x = fruits.index(32)
print(x)
```

<span style="color:yellow">
Note: The index() method only returns the first occurrence of the value.
</span>



### insert() 


```{python}
#Example
#Insert the value "orange" as the second element of the fruit list:

fruits = ['apple', 'banana', 'cherry']

fruits.insert(1, "orange")
print(fruits)
```

#### <span style="color:orange"> Definition and Usage </span>

The insert() method inserts the specified value at the specified position.

#### <span style="color:orange"> Syntax </span>

list.insert(pos, elmnt)

#### <span style="color:orange"> Parameter Values </span>

$$
\begin{array}{c|c}
\text{Parameter} & \text{Description}  \\ \hline
\text{pos} & \text{Required. A number specifying in which position to insert the value} \\
\text{elmnt} & \text{	Required. An element of any type (string, number, object etc.)} 
\end{array}
$$
	

### pop()


```{python}
#Example
#Remove the second element of the fruit list:

fruits = ['apple', 'banana', 'cherry']

fruits.pop(1)
print(fruits)
```

#### <span style="color:orange"> Definition and Usage </span>

The pop() method removes the element at the specified position.

#### <span style="color:orange"> Syntax </span>

list.pop(pos)

#### <span style="color:orange"> Parameter Values </span>


$$
\begin{array}{c|c}
\text{Parameter} & \text{Description}  \\ \hline
\text{pos} & \text{Optional. A number specifying the position of the element you want to remove, default value is -1, which returns the last item} 
\end{array}
$$

#### <span style="color:orange"> More Examples </span>



```{python}
#Example
#Return the removed element:

fruits = ['apple', 'banana', 'cherry']

x = fruits.pop(1)
print(x)
```

<span style="color:yellow"> 
Note: The pop() method returns removed value.
</span>



### remove() 


```{python}
#Example
#Remove the "banana" element of the fruit list:

fruits = ['apple', 'banana', 'cherry']

fruits.remove("banana")
print(fruits)
```

#### <span style="color:orange"> Definition and Usage </span>

The remove() method removes the first occurrence of the element with the specified value.

#### <span style="color:orange"> Syntax </span>

list.remove(elmnt)

#### <span style="color:orange"> Parameter Values </span>

$$
\begin{array}{c|c}
\text{Parameter} & \text{Description}  \\ \hline
\text{elmnt} & \text{Required. Any type (string, number, list etc.) The element you want to remove} 
\end{array}
$$
	

### reverse() 

```{python}
#Example
#Reverse the order of the fruit list:

fruits = ['apple', 'banana', 'cherry']

fruits.reverse()
print(fruits)
```


#### <span style="color:orange">Definition and Usage  </span>

The reverse() method reverses the sorting order of the elements.

#### <span style="color:orange"> Syntax </span>

list.reverse()

#### <span style="color:orange"> Parameter Values </span>

No parameters


#### <span style="color:orange"> Related Functions </span>

The buil-in function reversed() returns a reversed iterator object.




###  reversed() 

```{python}
#Example
#Reverse the sequence of a list, and print each item:

alph = ["a", "b", "c", "d"]
ralph = reversed(alph)
for x in ralph:
  print(x)
```


#### <span style="color:orange"> Definition and Usage </span>

The reversed() function returns a reversed iterator object.

#### <span style="color:orange"> Syntax </span>

reversed(sequence)

#### <span style="color:orange"> Parameter Values </span>

$$
\begin{array}{c|c}
\text{Parameter} & \text{Description}  \\ \hline
\text{sequence} & \text{Required. Any iterable object} 
\end{array}
$$
	

#### <span style="color:orange"> Related Functions </span>

The iter() function returns an iterator object.

The list.reverse() method reverses a List.


### iter() 

```{python}
#Example
#Create an iterator object, and print the items:

x = iter(["apple", "banana", "cherry"])
print(next(x))
print(next(x))
print(next(x))
```


#### <span style="color:orange"> Definition and Usage </span>

The iter() function returns an iterator object.

#### <span style="color:orange"> Syntax </span>

iter(object, sentinel)

#### <span style="color:orange"> Parameter Values  </span>

$$
\begin{array}{c|c}
\text{Parameter} & \text{Description}  \\ \hline
\text{object} & \text{Required. An iterable object} \\
\text{sentinel} & \text{Optional. If the object is a callable object the iteration will stop when the returned value is the same as the sentinel}
\end{array}
$$
	
	

#### <span style="color:orange"> Related Functions </span>

The reversed() function returns a reversed iterator object.





###  sort()

```{python}
#Example
#Sort the list alphabetically:

cars = ['Ford', 'BMW', 'Volvo']

cars.sort()
print(cars)
```


#### <span style="color:orange"> Definition and Usage </span>

The sort() method sorts the list ascending by default.

You can also make a function to decide the sorting criteria(s).

#### <span style="color:orange"> Syntax </span>

list.sort(reverse=True|False, key=myFunc)

#### <span style="color:orange"> Parameter Values </span>

$$
\begin{array}{c|c}
\text{Parameter} & \text{Description}  \\ \hline
\text{reverse} & \text{Optional. reverse=True will sort the list descending. Default is reverse=False} \\
\text{key} & \text{Optional. A function to specify the sorting criteria(s)
More Examples}
\end{array}
$$


	

```{python}
#Example
#Sort the list descending:

cars = ['Ford', 'BMW', 'Volvo']

cars.sort(reverse=True)
print(cars)
```



```{python}
#Example
#Sort the list by the length of the values:

# A function that returns the length of the value:
def myFunc(e):
  return len(e)

cars = ['Ford', 'Mitsubishi', 'BMW', 'VW']

cars.sort(key=myFunc)
print(cars)
```



```{python}
#Example
#Sort a list of dictionaries based on the "year" value of the dictionaries:

# A function that returns the 'year' value:
def myFunc(e):
  return e['year']

cars = [
  {'car': 'Ford', 'year': 2005},
  {'car': 'Mitsubishi', 'year': 2000},
  {'car': 'BMW', 'year': 2019},
  {'car': 'VW', 'year': 2011}
]

cars.sort(key=myFunc)
print(cars)
```



```{python}
#Example
#Sort the list by the length of the values and reversed:

# A function that returns the length of the value:
def myFunc(e):
  return len(e)

cars = ['Ford', 'Mitsubishi', 'BMW', 'VW']

cars.sort(reverse=True, key=myFunc)
print(cars)

```








## Contact us

Contact me at masoudfaridi@modares.ac.ir or masoud1faridi@gmail.com

