---
title: "Python Cheat Sheets-0001-Variables-MasoudF"
output: 
  html_document:
    code_folding: show
    theme:
      bg: "#202123"
      fg: "#B8BCC2"
      primary: "#EA80FC"
      secondary: "#00DAC6"
      base_font:
        google: Prompt
      heading_font:
        google: Proza Libre
---

```{r setup, include=FALSE}
if (requireNamespace("thematic")) 
  thematic::thematic_rmd(font = "auto")
library(reticulate)
#reticulate::use_python("C:/Program Files/Python310/python.exe")
```

## What is Python?



Python is a popular programming language. It was created by Guido van Rossum, and released in 1991.

It is used for:

* web development (server-side),
* software development,
* mathematics,
* system scripting.


## What can Python do?

* Python can be used on a server to create web applications.
* Python can be used alongside software to create workflows.
* Python can connect to database systems. It can also read and modify files.
* Python can be used to handle big data and perform complex mathematics.
* Python can be used for rapid prototyping, or for production-ready software development.

## Why Python?

* Python works on different platforms (Windows, Mac, Linux, Raspberry Pi, etc).
* Python has a simple syntax similar to the English language.
* Python has syntax that allows developers to write programs with fewer lines than some other programming languages.
* Python runs on an interpreter system, meaning that code can be executed as soon as it is written. This means that prototyping can be very quick.
* Python can be treated in a procedural way, an object-oriented way or a functional way.

## Good to know 

The most recent major version of Python is Python 3, which we shall be using in this tutorial. However, Python 2, although not being updated with anything other than security updates, is still quite popular.
In this tutorial Python will be written in a text editor. It is possible to write Python in an Integrated Development Environment, such as Thonny, Pycharm, Netbeans or Eclipse which are particularly useful when managing larger collections of Python files.

## Python Syntax compared to other programming languages

* Python was designed for readability, and has some similarities to the English language with influence from mathematics.
* Python uses new lines to complete a command, as opposed to other programming languages which often use semicolons or parentheses.
* Python relies on indentation, using whitespace, to define scope; such as the scope of loops, functions and classes. Other programming languages often use curly-brackets for this purpose.

## Python Variables {.tabset .tabset-pills}

Variables are containers for storing data values.


### Creating Variables

Python has no command for declaring a variable.

A variable is created the moment you first assign a value to it.

```{python}
x = 5
y = "John"
print(x)
print(y)
```
Variables do not need to be declared with any particular type, and can even change type after they have been set.


```{python}
x = 4       # x is of type int
x = "Sally" # x is now of type str
print(x)
```

### Variable equality part 1

#### is and == operators

$$
\begin{array}{c|c|c|c}
\text{identity operator} &  \text{memory address} & \text{is} & \text{is not} \\ \hline
\text{equality operator} &  \text{object state(data)} & == & !=
\end{array}
$$

```{python}
a = 10       
b = 10  
a is b  # memory address, identity operator 
a == b  # object state(data), equality operator 
```

```{python}
a = "hello"       
b = "hello"  
a is b  #
a == b
```

```{python}
a = "hello world"       
b = "hello world"  
a is b  #
a == b
```

```{python}
a = [1, 2, 3]     
b = [1, 2, 3]  
a is b
a == b
```

```{python}
a = 10       
b = 10.0 
type(a)
type(b)
a is b  # memory address, identity operator 
a == b  # object state(data), equality operator 
```

### Variable equality part 2

```{python}
a=0.25+0.25+0.25
b=0.75
a==b
```

```{python}
a=0.1+0.1+0.1
b=0.3
a==b
```
```{python}
a=1000.1+1000.1+1000.1
b=1000.3
a==b
```
```{python}
import math
a=0.1+0.1+0.1
b=0.3
a==b
math.isclose(a,b)
```
```{python}
import math
a=10000.1+10000.1+10000.1
b=30000.3
a==b
math.isclose(a,b)
```


#### Casting

If you want to specify the data type of a variable, this can be done with casting.

```{python}
x = str(3)    # x will be '3'
y = int(3)    # y will be 3
z = float(3)  # z will be 3.0
```


#### Get the Type

```{python}
x = 5
y = "John"
print(type(x))
print(type(y))
```



### Variable Names

A variable can have a short name (like x and y) or a more descriptive name (age, carname, total_volume).

Rules for Python variables:

* A variable name must start with a letter or the underscore character,
* A variable name cannot start with a number,
* A variable name can only contain alpha-numeric characters and underscores (A-z, 0-9, and _ ),
* Variable names are case-sensitive (age, Age and AGE are three different variables).

```{python}
a = "MyFolder"
print(a.isidentifier())
b = "Demo002"
print(b.isidentifier())
c = "2bring"
print(c.isidentifier())
d = "my demo"
print(d.isidentifier())
```



#### Multi Words Variable Names

Variable names with more than one word can be difficult to read.

There are several techniques you can use to make them more readable:


#### Camel Case

Each word, except the first, starts with a capital letter:

```{python}
myVariableName = "John"
```


#### Pascal Case

Each word starts with a capital letter:

```{python}
MyVariableName = "John"
```

#### Snake Case

Each word is separated by an underscore character:
```{python}
my_variable_name = "John"
```


### Assign Multiple Values


#### Many Values to Multiple Variables

Python allows you to assign values to multiple variables in one line:

```{python}
x, y, z = "Orange", "Banana", "Cherry"
print(x)
print(y)
print(z)
```

<span style="color:yellow;">Note: Make sure the number of variables matches the number of values, or else you will get an error.</span>


#### One Value to Multiple Variables

And you can assign the same value to multiple variables in one line:

```{python}
x = y = z = "Orange"
print(x)
print(y)
print(z)
```

#### Unpack a Collection

If you have a collection of values in a list, tuple etc. Python allows you extract the values into variables. This is called unpacking.

```{python}
fruits = ["apple", "banana", "cherry"]
x, y, z = fruits
print(x)
print(y)
print(z)
```

### Global Variables


Variables that are created outside of a function (as in all of the examples above) are known as global variables.

Global variables can be used by everyone, both inside of functions and outside.



```{python}
#Example
#Create a variable outside of a function, and use it inside the function
x = "awesome"
def myfunc():
  print("Python is " + x)
myfunc()
```


If you create a variable with the same name inside a function, this variable will be local, and can only be used inside the function. The global variable with the same name will remain as it was, global and with the original value.

```{python}
#Example
#Create a variable inside a function, with the same name as the global variable
x = "awesome"
def myfunc():
  x = "fantastic"
  print("Python is " + x)
myfunc()
print("Python is " + x)
```


#### The global Keyword

Normally, when you create a variable inside a function, that variable is local, and can only be used inside that function.

To create a global variable inside a function, you can use the global keyword.


```{python}
#Example
#If you use the global keyword, the variable belongs to the global scope:
def myfunc():
  global x
  x = "fantastic"
myfunc()
print("Python is " + x)
```


Also, use the global keyword if you want to change a global variable inside a function.

```{python}
#Example
#To change the value of a global variable inside a function, 
#refer to the variable by using the global keyword:

x = "awesome"
def myfunc():
  global x
  x = "fantastic"
myfunc()
print("Python is " + x)
```



### Data Types


#### Built-in Data Types

In programming, data type is an important concept.

Variables can store data of different types, and different types can do different things.

Python has the following data types built-in by default, in these categories:

* Text Type:	str
* TNumeric Types:	int, float, complex
* TSequence Types:	list, tuple, range
* TMapping Type:	dict
* TSet Types:	set, frozenset
* TBoolean Type:	bool
* TBinary Types:	bytes, bytearray, memoryview


#### Getting the Data Type
You can get the data type of any object by using the type() function:


```{python}
#Example
#Print the data type of the variable x:
x = 5
print(type(x))
```


#### Setting the Data Type


In Python, the data type is set when you assign a value to a variable:



```{python}
x = "Hello World"	#str
x = str("Hello World")	#str	
############################
x = 20	#int
x = int(20)	#int
############################
x = 20.5	#float
x = float(20.5)	#float	
############################
x = 1j #complex	
x = complex(1j)	#complex	
############################
x = ["apple", "banana", "cherry"]	#list
x = list(("apple", "banana", "cherry"))	#list
############################
x = ("apple", "banana", "cherry")	#tuple
x = tuple(("apple", "banana", "cherry"))	#tuple	
############################
x = range(6)	#range	
x = range(6)	#range
############################
x = {"name" : "John", "age" : 36}	#dict	
x = dict(name="John", age=36)	#dict
############################
x = {"apple", "banana", "cherry"}	#set	
x = set(("apple", "banana", "cherry"))	#set
############################
x = frozenset({"apple", "banana", "cherry"})	#frozenset
x = frozenset(("apple", "banana", "cherry"))	#frozenset
############################
x = True	#bool	
x = bool(5)	#bool
############################
x = b"Hello"	#bytes	
x = bytes(5)	#bytes
############################
x = bytearray(5)	#bytearray	
x = bytearray(5)	#bytearray	
############################
x = memoryview(bytes(5))	#memoryview
x = memoryview(bytes(5))	#memoryview
```


	
### Python Numbers
There are three numeric types in Python:

* int
* float
* complex

Variables of numeric types are created when you assign a value to them:

```{python}
#Example
x = 1    # int
y = 2.8  # float
z = 1j   # complex
```
To verify the type of any object in Python, use the type() function:

```{python}
#Example
print(type(x))
print(type(y))
print(type(z))
```

#### Int

Int, or integer, is a whole number, positive or negative, without decimals, of unlimited length.

```{python}
#Example
#Integers:

x = 1
y = 35656222554887711
z = -3255522

print(type(x))
print(type(y))
print(type(z))
```

#### Float

Float, or "floating point number" is a number, positive or negative, containing one or more decimals.

```{python}
#Example
#Floats:

x = 1.10
y = 1.0
z = -35.59

print(type(x))
print(type(y))
print(type(z))
```
Float can also be scientific numbers with an "e" to indicate the power of 10.

```{python}
#Example
#Floats:

x = 35e3
y = 12E4
z = -87.7e100

print(type(x))
print(type(y))
print(type(z))
```

#### Complex

Complex numbers are written with a "j" as the imaginary part:

```{python}
#Example
#Complex:
x = 3+5j
y = 5j
z = -5j

print(type(x))
print(type(y))
print(type(z))
```

#### Type Conversion
You can convert from one type to another with the int(), float(), and complex() methods:

```{python}
#Example
#Convert from one type to another:

x = 1    # int
y = 2.8  # float
z = 1j   # complex

#convert from int to float:
a = float(x)

#convert from float to int:
b = int(y)

#convert from int to complex:
c = complex(x)

print(a)
print(b)
print(c)

print(type(a))
print(type(b))
print(type(c))
```


<span style="color:yellow;">
Note: You cannot convert complex numbers into another number type.
</span>


```{python}
x=range(6)
print(type(x))
print(x)
print(*x)
```
<span style="color:yellow;">
print(*range(6))
</span>


#### Random Number

Python does not have a random() function to make a random number, but Python has a built-in module called random that can be used to make random numbers:

```{python}
#Example
#Import the random module, and display a random number between 1 and 9:

import random

print(random.randrange(1, 10))
```	
	
	
### Casting


####	Specify a Variable Type

There may be times when you want to specify a type on to a variable. This can be done with casting. Python is an object-orientated language, and as such it uses classes to define data types, including its primitive types.

#### Casting in python is therefore done using constructor functions:

* int() - constructs an integer number from an integer literal, a float literal (by removing all decimals), or a string literal (providing the string represents a whole number)
* float() - constructs a float number from an integer literal, a float literal or a string literal (providing the string represents a float or an integer)
* str() - constructs a string from a wide variety of data types, including strings, integer literals and float literals

```{python}
#Example
#Integers:

x = int(1)   # x will be 1
y = int(2.8) # y will be 2
z = int("3") # z will be 3
```

```{python}
#Example
#Floats:

x = float(1)     # x will be 1.0
y = float(2.8)   # y will be 2.8
z = float("3")   # z will be 3.0
w = float("4.2") # w will be 4.2
```

```{python}
#Example
#Strings:

x = str("s1") # x will be 's1'
y = str(2)    # y will be '2'
z = str(3.0)  # z will be '3.0'
```	

### ref count

```{python}
import sys
import ctypes
a=[1,2,3,7]
b=a
a.append(-1)
a
b
b.append(-2)
a
```


```{python}
#import sys
#import ctypes
#a=[1,2,30]
#ctypes.c_int.from_address(id(a)).value
#1
#sys.getrefcount(a)-1
#1
#b=a
#ctypes.c_int.from_address(id(a)).value
#2
#sys.getrefcount(a)-1
#2
````
